// Ported from journeysnudgesemi/emi-conversions-prototype.html's
// dcConfirmAddNode / dcConfirmEditNode / dcRemoveEdge / dcRemoveRoot /
// dcConfirmConnectExisting / dcReplaceAutoNode — reworked from mutating a
// global `dripWiz` object into a useReducer-compatible pure reducer.
// Every action below clones its input graph once, then runs the same
// mutate-style graph-op functions against that clone — same algorithms,
// new mutation target, per the migration plan.
import type { DripGraph, DripGoal } from '../data/graphTypes';
import type { DcNodeType } from '../data/nodeMeta';
import { DC_EVENT_ENTITY, DC_PROMOTED_ATTR } from '../data/sharedConstants';
import { dcNewEdgeId, dcNewNodeId } from './idGen';
import { dcGarbageCollect, dcReconcileBranchEdges, dcRemoveEdge as dcRemoveEdgeOp, dcRemoveRoot as dcRemoveRootOp } from './graphOps';
import { dcDecisionBranchSummary, dcGoalLabel, dcRecomputeLabelMeta } from './labelMeta';

function cloneGraph(graph: DripGraph): DripGraph {
  return { nodes: structuredClone(graph.nodes), edges: structuredClone(graph.edges), rootId: graph.rootId };
}

// Where a new node attaches: the very first node in the campaign, filling
// an existing open slot, or growing a brand-new leaf off an existing node.
export type DcAddingAt = { kind: 'root' } | { kind: 'edge'; edgeId: string } | { kind: 'growLeaf'; nodeId: string };

// Builds the new node (via dcRecomputeLabelMeta, so label/meta logic lives
// in exactly one place, shared with editing), then any type-specific
// auto-children as real graph nodes/edges (a Send's own goal-check, a Wait
// Until's outcome check, a Split's auto Yes-branch, a Random/Decision
// Split's open arms), then attaches the whole thing to whichever
// slot/leaf this add action started from.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function dcConfirmAddNode(graph: DripGraph, type: DcNodeType, p: any, addingAt: DcAddingAt, goal: DripGoal | null): DripGraph {
  const next = cloneGraph(graph);
  const { label, meta } = dcRecomputeLabelMeta(type, p, goal);
  const id = dcNewNodeId();
  next.nodes[id] = { id, type, label, meta, _config: structuredClone(p), autoGenerated: false };

  // Goal check fires after every step that represents either a real send
  // (Send, Channel Failover) or real time passing (Pause) — not just after
  // a Send. A customer can convert on their own while a campaign is
  // mid-wait, and without a check right after the Pause, the next
  // scheduled action would fire blindly regardless of whether they'd
  // already hit the goal. Wait Until is the one exception — it already has
  // its own real outcome check below, a more precise version of this same
  // idea, not something to layer a second generic check on top of.
  if (type === 'SEND' || type === 'CHANNEL_FAILOVER' || type === 'PAUSE') {
    const question = (dcGoalLabel(goal) || 'Goal') + '?';
    const splitId = dcNewNodeId();
    const goalId = dcNewNodeId();
    next.nodes[splitId] = { id: splitId, type: 'SPLIT', label: question, meta: 'Goal check, auto-inserted after every Send', _config: null, autoGenerated: false };
    next.nodes[goalId] = { id: goalId, type: 'GOAL_EXIT', label: question.replace(/\?$/, ''), meta: '', _config: null, autoGenerated: true };
    next.edges.push({ id: dcNewEdgeId(), from: id, to: splitId, branchLabel: '', autoGenerated: false });
    next.edges.push({ id: dcNewEdgeId(), from: splitId, to: goalId, branchLabel: 'Yes', autoGenerated: true });
    next.edges.push({ id: dcNewEdgeId(), from: splitId, to: null, branchLabel: 'No', autoGenerated: false });
  } else if (type === 'WAIT_UNTIL') {
    // The event firing at all is only "success" when it's unambiguous
    // (Card Activated, RP Redeemed). For anything with a real outcome
    // attribute (EMI Request's New Status — Successful/Failed/Expired/
    // Cancelled all fire the SAME event), auto-exiting straight to
    // Goal-Based Exit would silently mislabel a Failed resolution as
    // success — auto-insert a real outcome check instead.
    const entity = DC_EVENT_ENTITY[p.eventCategory];
    const statusAttr = DC_PROMOTED_ATTR[entity];
    if (statusAttr) {
      const goalMatchesThisEvent = goal && goal.eventCategory === p.eventCategory && goal.eventType === p.eventType;
      const goalCond = goalMatchesThisEvent ? (goal!.conditions || []).find((c) => c.attribute === statusAttr) : null;
      const splitId = dcNewNodeId();
      if (goalCond) {
        next.nodes[splitId] = { id: splitId, type: 'SPLIT', label: `${statusAttr} = ${goalCond.value}?`, meta: 'Outcome check, auto-inserted after Wait Until', _config: null, autoGenerated: true };
        const goalExitId = dcNewNodeId();
        const exitId = dcNewNodeId();
        next.nodes[goalExitId] = { id: goalExitId, type: 'GOAL_EXIT', label: dcGoalLabel(goal)!, meta: '', _config: null, autoGenerated: true };
        next.nodes[exitId] = { id: exitId, type: 'EXIT', label: `Resolved, but not to the goal outcome (${statusAttr} ≠ ${goalCond.value})`, meta: '', _config: null, autoGenerated: false };
        next.edges.push({ id: dcNewEdgeId(), from: id, to: splitId, branchLabel: '', autoGenerated: true });
        next.edges.push({ id: dcNewEdgeId(), from: splitId, to: goalExitId, branchLabel: 'Yes', autoGenerated: true });
        next.edges.push({ id: dcNewEdgeId(), from: splitId, to: exitId, branchLabel: 'No', autoGenerated: false });
      } else {
        // Waiting on a multi-outcome event that ISN'T what the Goal is
        // defined against (or no Goal set at all) — no correct default
        // here, so don't guess. Leave both branches open.
        next.nodes[splitId] = { id: splitId, type: 'SPLIT', label: `${statusAttr}?`, meta: 'Define what counts as success for this outcome — not the campaign Goal, so nothing is auto-filled', _config: null, autoGenerated: true };
        next.edges.push({ id: dcNewEdgeId(), from: id, to: splitId, branchLabel: '', autoGenerated: true });
        next.edges.push({ id: dcNewEdgeId(), from: splitId, to: null, branchLabel: 'Success outcome', autoGenerated: false });
        next.edges.push({ id: dcNewEdgeId(), from: splitId, to: null, branchLabel: 'Other outcome', autoGenerated: false });
      }
    } else {
      const goalExitId = dcNewNodeId();
      next.nodes[goalExitId] = { id: goalExitId, type: 'GOAL_EXIT', label, meta: '', _config: null, autoGenerated: true };
      next.edges.push({ id: dcNewEdgeId(), from: id, to: goalExitId, branchLabel: 'Yes', autoGenerated: true });
    }
    next.edges.push({ id: dcNewEdgeId(), from: id, to: null, branchLabel: 'No', autoGenerated: false });
  } else if (type === 'SPLIT') {
    const goalExitId = dcNewNodeId();
    next.nodes[goalExitId] = { id: goalExitId, type: 'GOAL_EXIT', label: label.replace(/\?$/, ''), meta: '', _config: null, autoGenerated: true };
    next.edges.push({ id: dcNewEdgeId(), from: id, to: goalExitId, branchLabel: 'Yes', autoGenerated: true });
    next.edges.push({ id: dcNewEdgeId(), from: id, to: null, branchLabel: 'No', autoGenerated: false });
  } else if (type === 'DECISION_SPLIT') {
    // One open edge per real branch, evaluated top-to-bottom on the canvas
    // the same order they're listed here, plus one final fixed "Anything
    // else" catch-all edge.
    p.branches.forEach((b: { id?: string; label: string }) => {
      next.edges.push({ id: dcNewEdgeId(), from: id, to: null, branchLabel: `${b.label} (${dcDecisionBranchSummary(p, b as never)})`, branchId: b.id, autoGenerated: false });
    });
    next.edges.push({ id: dcNewEdgeId(), from: id, to: null, branchLabel: 'Anything else', autoGenerated: false });
  } else if (type === 'RANDOM_SPLIT') {
    p.branches.forEach((b: { id?: string; label: string; pct: number }) => {
      next.edges.push({ id: dcNewEdgeId(), from: id, to: null, branchLabel: `${b.label} (${b.pct}%)`, branchId: b.id, autoGenerated: false });
    });
  }

  if (addingAt.kind === 'root') next.rootId = id;
  else if (addingAt.kind === 'edge') {
    const e = next.edges.find((e) => e.id === addingAt.edgeId);
    if (e) e.to = id;
  } else if (addingAt.kind === 'growLeaf') {
    next.edges.push({ id: dcNewEdgeId(), from: addingAt.nodeId, to: id, branchLabel: '', autoGenerated: false });
  }

  return next;
}

// Recomputes only label+meta for an existing node's new config and
// reconciles branch edges where relevant — never touches unrelated
// children. Editing must never regenerate a subtree; whatever's already
// built under a node stays exactly as it was.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function dcConfirmEditNode(graph: DripGraph, nodeId: string, type: DcNodeType, p: any, goal: DripGoal | null): DripGraph {
  const next = cloneGraph(graph);
  const node = next.nodes[nodeId];
  if (!node) return next;
  const prevConfig = node._config ? JSON.stringify(node._config) : null;
  const { label, meta } = dcRecomputeLabelMeta(type, p, goal);
  node.label = label;
  node.meta = meta;
  node._config = structuredClone(p);

  // Random Split / Decision Split branches are real outgoing edges —
  // whatever's been built under each arm must survive an edit, including
  // one that adds, removes, or inserts a branch in the middle.
  if (type === 'RANDOM_SPLIT') {
    dcReconcileBranchEdges(next, nodeId, p.branches, (b) => `${(b as { label: string }).label} (${(b as { pct: number }).pct}%)`, null);
  }
  if (type === 'DECISION_SPLIT') {
    dcReconcileBranchEdges(next, nodeId, p.branches, (b) => `${(b as { label: string }).label} (${dcDecisionBranchSummary(p, b as never)})`, 'Anything else');
  }

  // A Split's Yes-branch is auto-built as a GOAL_EXIT at creation time,
  // meaning "reaching this condition = the campaign's goal." Editing the
  // Split's own condition changes what "Yes" actually means — a stale,
  // untouched auto GOAL_EXIT left in place would keep implying the OLD
  // condition's success is still the campaign goal. Reset ONLY when the
  // condition genuinely changed, the Yes-target is still exactly the
  // untouched auto GOAL_EXIT dcConfirmAddNode produced (nothing built
  // under it), AND it isn't also reached from anywhere else (a real,
  // deliberate merge should never be undone by an unrelated edit).
  if (type === 'SPLIT' && prevConfig !== JSON.stringify(p)) {
    const yesEdge = next.edges.find((e) => e.from === nodeId && e.branchLabel === 'Yes');
    if (yesEdge && yesEdge.to) {
      const yesNode = next.nodes[yesEdge.to];
      const hasNoOutgoing = !next.edges.some((e) => e.from === yesEdge.to);
      const singleIncoming = next.edges.filter((e) => e.to === yesEdge.to).length === 1;
      if (yesNode && yesNode.type === 'GOAL_EXIT' && yesNode.autoGenerated && hasNoOutgoing && singleIncoming) {
        const oldTarget = yesEdge.to;
        yesEdge.to = null;
        dcGarbageCollect(next, oldTarget);
      }
    }
  }

  return next;
}

export function dcRemoveEdge(graph: DripGraph, edgeId: string): DripGraph {
  const next = cloneGraph(graph);
  dcRemoveEdgeOp(next, edgeId);
  return next;
}

export function dcRemoveRoot(graph: DripGraph): DripGraph {
  const next = cloneGraph(graph);
  dcRemoveRootOp(next);
  return next;
}

// "Connect to an Existing Step" — points a branch at a step that's already
// built, instead of rebuilding it. Adds one edge, creates no new node —
// since it's the SAME node afterward, editing it updates every path that
// reaches it.
export function dcConnectExisting(graph: DripGraph, addingAt: DcAddingAt, targetId: string): DripGraph {
  const next = cloneGraph(graph);
  if (addingAt.kind === 'edge') {
    const e = next.edges.find((e) => e.id === addingAt.edgeId);
    if (e) e.to = targetId;
  } else if (addingAt.kind === 'growLeaf') {
    next.edges.push({ id: dcNewEdgeId(), from: addingAt.nodeId, to: targetId, branchLabel: '', autoGenerated: false });
  }
  return next;
}
