// Ported scenario-for-scenario from this feature's original real-browser
// Playwright matrix (test_drip_full_matrix.js / test_drip_matrix_part2.js
// / verify_insert_branch.js, run against the plain-HTML prototype). Those
// scripts needed a real browser only because the logic lived inside
// onclick-string handlers mutating a global object — now that it's a pure
// reducer, the exact same scenarios run as fast, browser-free unit tests.
import { beforeEach, describe, expect, it } from 'vitest';
import type { DripGraph, DripGoal } from '../../src/data/graphTypes';
import { dcResetIdCounters } from '../../src/reducer/idGen';
import { dcGraphHasOpenBranches } from '../../src/reducer/graphOps';
import { dcConfirmAddNode, dcConfirmEditNode, dcRemoveEdge, dcRemoveGoalCheck, type DcAddingAt } from '../../src/reducer/campaignReducer';
import { dcDefaultConfig, dcAddFormValid } from '../../src/reducer/defaultConfig';

const EMPTY_GRAPH: DripGraph = { nodes: {}, edges: [], rootId: null };
// A real goal — the auto goal-check Split after Send/Pause is only
// inserted when one is actually defined (a goal-less campaign gets a
// plain open slot instead, since there'd be nothing real to check).
const TEST_GOAL: DripGoal = { eventCategory: 'Card Events', eventType: 'Card Activated', conditions: [] };

function addEntryEvent(graph: DripGraph, overrides: Record<string, unknown> = {}): DripGraph {
  const p = { ...dcDefaultConfig('ENTRY_EVENT', null), eventCategory: 'Journey Events', eventType: 'Pageload', ...overrides };
  return dcConfirmAddNode(graph, 'ENTRY_EVENT', p, { kind: 'root' }, null);
}

beforeEach(() => {
  dcResetIdCounters();
});

describe('Entry nodes', () => {
  // Node-design refinement pass: canvas = execution map, drawer = config
  // database. Eligibility conditions are real configuration detail (P2),
  // so a Segment's meta line never repeats them — the condition itself
  // still lives in _config, just not rendered on the card.
  it('Entry Segment meta omits condition detail — conditions stay in _config, not on canvas', () => {
    const p = { ...dcDefaultConfig('ENTRY_SEGMENT', null), conditions: [{ attribute: 'Status', operator: 'Equals', value: 'Active' }] };
    const g = dcConfirmAddNode(EMPTY_GRAPH, 'ENTRY_SEGMENT', p, { kind: 'root' }, null);
    expect(g.rootId).toBeTruthy();
    const root = g.nodes[g.rootId!];
    expect(root.type).toBe('ENTRY_SEGMENT');
    expect(root.meta).toBe('');
    expect((root._config as { conditions: unknown[] }).conditions).toHaveLength(1);
  });

  it('Entry Event sets the root', () => {
    const g = addEntryEvent(EMPTY_GRAPH);
    expect(g.rootId).toBeTruthy();
    expect(g.nodes[g.rootId!].type).toBe('ENTRY_EVENT');
  });

  it('Entry Segment with repeat on shows only the recurrence in meta — no entity, no condition detail', () => {
    const p = { ...dcDefaultConfig('ENTRY_SEGMENT', null), repeat: true, entity: 'Account', conditions: [{ attribute: 'Status', operator: 'Equals', value: 'Active' }] };
    const g = dcConfirmAddNode(EMPTY_GRAPH, 'ENTRY_SEGMENT', p, { kind: 'root' }, null);
    const root = g.nodes[g.rootId!];
    expect(root.meta).toContain('every month');
    expect(root.meta).not.toContain('Account');
    expect(root.meta).not.toContain('Status');
    expect(root.meta).not.toContain('undefined');
  });
});

describe('Send -> auto goal-check', () => {
  it('Send auto-inserts a GOAL_CHECK + GOAL_EXIT, both resolve independently when a second Send (with its own fallback) chains under No', () => {
    let g = addEntryEvent(EMPTY_GRAPH);
    const sendP = { ...dcDefaultConfig('SEND', null), name: 'Msg1', channel: 'WHATSAPP', account: 'IBL-Karix-Onb', templateId: 'CT-3310' };
    g = dcConfirmAddNode(g, 'SEND', sendP, { kind: 'growLeaf', nodeId: g.rootId! }, TEST_GOAL);
    expect(Object.keys(g.nodes).length).toBeGreaterThanOrEqual(3); // Entry + Send + auto GOAL_CHECK (+ GOAL_EXIT)

    const send = Object.values(g.nodes).find((n) => n.label === 'Msg1')!;
    const splitEdge = g.edges.find((e) => e.from === send.id)!;
    const split = g.nodes[splitEdge.to!];
    expect(split.type).toBe('GOAL_CHECK');
    expect(split.autoGenerated).toBe(true);
    const yesEdge = g.edges.find((e) => e.from === split.id && e.branchLabel === 'Yes')!;
    expect(g.nodes[yesEdge.to!].type).toBe('GOAL_EXIT');

    const noEdge = g.edges.find((e) => e.from === split.id && e.branchLabel === 'No')!;
    expect(noEdge.to).toBeNull();

    // chain a second Send, this one with a fallback channel configured,
    // under the No branch
    const fallbackSendP = { ...dcDefaultConfig('SEND', null), name: 'Msg2', channel: 'WHATSAPP', account: 'IBL-Karix-Txns', templateId: 'CT-3311', fallbackChannel: 'SMS', fallbackAccount: 'IBL-Karix-Txns', fallbackTemplateId: 'CT-3301' };
    g = dcConfirmAddNode(g, 'SEND', fallbackSendP, { kind: 'edge', edgeId: noEdge.id }, TEST_GOAL);
    const send2 = Object.values(g.nodes).find((n) => n.label === 'Msg2')!;
    expect((send2._config as typeof fallbackSendP).fallbackChannel).toBe('SMS');
    const send2SplitEdge = g.edges.find((e) => e.from === send2.id)!;
    expect(g.nodes[send2SplitEdge.to!].type).toBe('GOAL_CHECK');
  });
});

describe('Pause', () => {
  it('Pause gets its own auto GOAL_CHECK when a goal is defined', () => {
    let g = addEntryEvent(EMPTY_GRAPH);
    g = dcConfirmAddNode(g, 'PAUSE', { duration: 3, unit: 'days' }, { kind: 'growLeaf', nodeId: g.rootId! }, TEST_GOAL);
    const pause = Object.values(g.nodes).find((n) => n.type === 'PAUSE')!;
    const edge = g.edges.find((e) => e.from === pause.id)!;
    expect(g.nodes[edge.to!].type).toBe('GOAL_CHECK');
  });

  it('Pause gets a plain open slot, not a goal-check, when no goal is defined', () => {
    let g = addEntryEvent(EMPTY_GRAPH);
    g = dcConfirmAddNode(g, 'PAUSE', { duration: 3, unit: 'days' }, { kind: 'growLeaf', nodeId: g.rootId! }, null);
    const pause = Object.values(g.nodes).find((n) => n.type === 'PAUSE')!;
    const edge = g.edges.find((e) => e.from === pause.id)!;
    expect(edge.to).toBeNull();
  });
});

describe('Goal-check removal', () => {
  it('removing the auto goal-check Split reconnects its parent straight to whatever the No branch led to', () => {
    let g = addEntryEvent(EMPTY_GRAPH);
    const sendP = { ...dcDefaultConfig('SEND', null), name: 'Msg1', channel: 'WHATSAPP', account: 'IBL-Karix-Onb', templateId: 'CT-3310' };
    g = dcConfirmAddNode(g, 'SEND', sendP, { kind: 'growLeaf', nodeId: g.rootId! }, TEST_GOAL);
    const send = Object.values(g.nodes).find((n) => n.label === 'Msg1')!;
    const splitEdge = g.edges.find((e) => e.from === send.id)!;
    const splitId = splitEdge.to!;
    const noEdge = g.edges.find((e) => e.from === splitId && e.branchLabel === 'No')!;

    // Build something real under the No branch before removing the check.
    g = dcConfirmAddNode(g, 'PAUSE', { duration: 2, unit: 'days' }, { kind: 'edge', edgeId: noEdge.id }, TEST_GOAL);
    const pause = Object.values(g.nodes).find((n) => n.type === 'PAUSE')!;

    g = dcRemoveGoalCheck(g, splitId);
    expect(g.nodes[splitId]).toBeUndefined();
    const sendEdge = g.edges.find((e) => e.from === send.id)!;
    expect(sendEdge.to).toBe(pause.id);
  });
});

describe('Wait Until', () => {
  const goal: DripGoal = { eventCategory: 'EMI Events', eventType: 'EMI_STATUS_CHANGED', conditions: [{ attribute: 'New Status', operator: 'Equals', value: 'Successful' }] };

  it('promoted attribute matching the campaign Goal -> real outcome-check GOAL_CHECK', () => {
    let g = addEntryEvent(EMPTY_GRAPH, { eventCategory: 'Transaction Events', eventType: 'Transaction' });
    const p = { eventCategory: 'EMI Events', eventType: 'EMI_STATUS_CHANGED', duration: 7, unit: 'days', conditions: [] };
    g = dcConfirmAddNode(g, 'WAIT_UNTIL', p, { kind: 'growLeaf', nodeId: g.rootId! }, goal);
    const wu = Object.values(g.nodes).find((n) => n.type === 'WAIT_UNTIL')!;
    const toSplitEdge = g.edges.find((e) => e.from === wu.id && e.branchLabel === '')!;
    const split = g.nodes[toSplitEdge.to!];
    expect(split.type).toBe('GOAL_CHECK');
    const yes = g.edges.find((e) => e.from === split.id && e.branchLabel === 'Yes')!;
    const no = g.edges.find((e) => e.from === split.id && e.branchLabel === 'No')!;
    expect(g.nodes[yes.to!].type).toBe('GOAL_EXIT');
    expect(g.nodes[no.to!].type).toBe('EXIT');
  });

  // Regression: this used to auto-wire Yes -> GOAL_EXIT for ANY
  // unambiguous event (no promoted attribute), even with no campaign
  // Goal defined at all — surfaced directly by the user seeing a "Goal
  // Reached" node on a Wait for Event step in a goal-less campaign. An
  // event firing is never automatically "the goal" on its own; it only
  // is when a real campaign Goal says so.
  it('unambiguous event (no promoted attribute), no campaign Goal -> Yes stays open, no GOAL_EXIT invented', () => {
    let g = addEntryEvent(EMPTY_GRAPH);
    const p = { eventCategory: 'Journey Events', eventType: 'Journey Progress', duration: 10, unit: 'days', conditions: [] };
    g = dcConfirmAddNode(g, 'WAIT_UNTIL', p, { kind: 'growLeaf', nodeId: g.rootId! }, null);
    const wu = Object.values(g.nodes).find((n) => n.type === 'WAIT_UNTIL')!;
    const yes = g.edges.find((e) => e.from === wu.id && e.branchLabel === 'Yes')!;
    expect(yes.to).toBeNull();
    expect(Object.values(g.nodes).some((n) => n.type === 'GOAL_EXIT')).toBe(false);
  });

  it('unambiguous event (no promoted attribute), campaign Goal matches this exact event -> Yes -> GOAL_EXIT', () => {
    const matchingGoal: DripGoal = { eventCategory: 'Journey Events', eventType: 'Journey Progress', conditions: [] };
    let g = addEntryEvent(EMPTY_GRAPH);
    const p = { eventCategory: 'Journey Events', eventType: 'Journey Progress', duration: 10, unit: 'days', conditions: [] };
    g = dcConfirmAddNode(g, 'WAIT_UNTIL', p, { kind: 'growLeaf', nodeId: g.rootId! }, matchingGoal);
    const wu = Object.values(g.nodes).find((n) => n.type === 'WAIT_UNTIL')!;
    const yes = g.edges.find((e) => e.from === wu.id && e.branchLabel === 'Yes')!;
    expect(g.nodes[yes.to!].type).toBe('GOAL_EXIT');
  });

  it('unambiguous event (no promoted attribute), campaign Goal defined but for a DIFFERENT event -> Yes stays open', () => {
    const otherGoal: DripGoal = { eventCategory: 'EMI Events', eventType: 'EMI_STATUS_CHANGED', conditions: [] };
    let g = addEntryEvent(EMPTY_GRAPH);
    const p = { eventCategory: 'Journey Events', eventType: 'Journey Progress', duration: 10, unit: 'days', conditions: [] };
    g = dcConfirmAddNode(g, 'WAIT_UNTIL', p, { kind: 'growLeaf', nodeId: g.rootId! }, otherGoal);
    const wu = Object.values(g.nodes).find((n) => n.type === 'WAIT_UNTIL')!;
    const yes = g.edges.find((e) => e.from === wu.id && e.branchLabel === 'Yes')!;
    expect(yes.to).toBeNull();
  });

  it('promoted attribute NOT matching the campaign Goal -> both branches open, no guess', () => {
    const otherGoal: DripGoal = { eventCategory: 'Journey Events', eventType: 'Journey Progress', conditions: [] };
    let g = addEntryEvent(EMPTY_GRAPH, { eventCategory: 'Transaction Events', eventType: 'Transaction' });
    const p = { eventCategory: 'EMI Events', eventType: 'EMI_STATUS_CHANGED', duration: 5, unit: 'days', conditions: [] };
    g = dcConfirmAddNode(g, 'WAIT_UNTIL', p, { kind: 'growLeaf', nodeId: g.rootId! }, otherGoal);
    const wu = Object.values(g.nodes).find((n) => n.type === 'WAIT_UNTIL')!;
    const toSplitEdge = g.edges.find((e) => e.from === wu.id && e.branchLabel === '')!;
    const split = g.nodes[toSplitEdge.to!];
    const openEdges = g.edges.filter((e) => e.from === split.id && e.to === null);
    expect(openEdges.length).toBe(2);
  });
});

describe('Split (Condition) — no "Goal reached" basis anymore', () => {
  it('a user-built Condition never auto-wires its Yes branch to Goal Reached', () => {
    // Previously this exact shape (basis: 'Goal reached') produced an
    // auto GOAL_EXIT under Yes — Phase 1 moved that entirely into the
    // separate GOAL_CHECK type, so a Condition's Yes/No are always both
    // plain open slots, regardless of what it's conditioned on.
    const goal: DripGoal = { eventCategory: 'EMI Events', eventType: 'EMI_STATUS_CHANGED', conditions: [{ attribute: 'New Status', operator: 'Equals', value: 'Successful' }] };
    let g = addEntryEvent(EMPTY_GRAPH);
    const p = { customSource: 'Previous step outcome', outcome: 'Clicked', customConditions: [] };
    g = dcConfirmAddNode(g, 'SPLIT', p, { kind: 'growLeaf', nodeId: g.rootId! }, goal);
    const split = Object.values(g.nodes).find((n) => n.type === 'SPLIT')!;
    const yesEdge = g.edges.find((e) => e.from === split.id && e.branchLabel === 'Yes')!;
    const noEdge = g.edges.find((e) => e.from === split.id && e.branchLabel === 'No')!;
    expect(yesEdge.to).toBeNull();
    expect(noEdge.to).toBeNull();
    expect(Object.values(g.nodes).some((n) => n.type === 'GOAL_EXIT')).toBe(false);
  });

  it('Custom condition split (Account attribute) builds a real Yes/No pair', () => {
    let g = addEntryEvent(EMPTY_GRAPH);
    const p = { customSource: 'Account attribute', outcome: '', customConditions: [{ attribute: 'Engagement Tier', operator: 'Any of', values: ['Dormant'] }] };
    g = dcConfirmAddNode(g, 'SPLIT', p, { kind: 'growLeaf', nodeId: g.rootId! }, null);
    const split = Object.values(g.nodes).find((n) => n.type === 'SPLIT')!;
    expect(split).toBeTruthy();
    expect(g.edges.some((e) => e.from === split.id && e.branchLabel === 'Yes')).toBe(true);
    expect(g.edges.some((e) => e.from === split.id && e.branchLabel === 'No')).toBe(true);
  });

  it('Goal Reached can still be added manually on a Condition branch arm', () => {
    let g = addEntryEvent(EMPTY_GRAPH);
    const p = { customSource: 'Account attribute', outcome: '', customConditions: [{ attribute: 'Engagement Tier', operator: 'Any of', values: ['Dormant'] }] };
    g = dcConfirmAddNode(g, 'SPLIT', p, { kind: 'growLeaf', nodeId: g.rootId! }, null);
    const split = Object.values(g.nodes).find((n) => n.type === 'SPLIT')!;
    const yesEdge = g.edges.find((e) => e.from === split.id && e.branchLabel === 'Yes')!;
    g = dcConfirmAddNode(g, 'GOAL_EXIT', { reason: 'Reactivated' }, { kind: 'edge', edgeId: yesEdge.id }, null);
    expect(g.nodes[g.edges.find((e) => e.id === yesEdge.id)!.to!].type).toBe('GOAL_EXIT');
  });
});

describe('Decision Split', () => {
  it('2 branches + catch-all, correct summary labels', () => {
    let g = addEntryEvent(EMPTY_GRAPH);
    const p = {
      name: 'Decision', source: 'Account attribute', attribute: 'Milestone Progress %', outcome: 'Clicked',
      branches: [
        { id: 'b1', label: 'Branch 1', operator: 'Between', value: '5', value2: '20' },
        { id: 'b2', label: 'Branch 2', operator: 'Between', value: '21', value2: '50' },
      ],
    };
    g = dcConfirmAddNode(g, 'DECISION_SPLIT', p, { kind: 'growLeaf', nodeId: g.rootId! }, null);
    const ds = Object.values(g.nodes).find((n) => n.type === 'DECISION_SPLIT')!;
    expect(ds.label).toBe('Milestone Progress %');
    expect(ds.meta).toBe('2 branches + catch-all');
    const labels = g.edges.filter((e) => e.from === ds.id).map((e) => e.branchLabel);
    expect(labels).toEqual(['Branch 1 (5–20)', 'Branch 2 (21–50)', 'Anything else']);
  });

  it('dcAddFormValid blocks when a branch value is missing', () => {
    const p = { ...dcDefaultConfig('DECISION_SPLIT', null), attribute: 'Milestone Progress %' };
    expect(dcAddFormValid('DECISION_SPLIT', p)).toBe(false); // branch values empty by default
  });
});

describe('Random Split', () => {
  it('N branches become N open edges', () => {
    let g = addEntryEvent(EMPTY_GRAPH);
    const p = { name: 'Channel test', branches: [{ id: 'a', label: 'A', pct: 34 }, { id: 'b', label: 'B', pct: 33 }, { id: 'c', label: 'C', pct: 33 }] };
    g = dcConfirmAddNode(g, 'RANDOM_SPLIT', p, { kind: 'growLeaf', nodeId: g.rootId! }, null);
    const rs = Object.values(g.nodes).find((n) => n.type === 'RANDOM_SPLIT')!;
    expect(g.edges.filter((e) => e.from === rs.id).length).toBe(3);
  });

  it('dcAddFormValid requires percentages to sum to 100', () => {
    const p = { branches: [{ pct: 30 }, { pct: 30 }] };
    expect(dcAddFormValid('RANDOM_SPLIT', p)).toBe(false);
    expect(dcAddFormValid('RANDOM_SPLIT', { branches: [{ pct: 60 }, { pct: 40 }] })).toBe(true);
  });
});

describe('Send fallback channel validation', () => {
  it('a Send with no fallback configured only needs its own account/template', () => {
    expect(dcAddFormValid('SEND', { channel: 'WHATSAPP', account: 'x', templateId: 'CT-1', fallbackChannel: '' })).toBe(true);
    expect(dcAddFormValid('SEND', { channel: 'WHATSAPP', account: '', templateId: '', fallbackChannel: '' })).toBe(false);
  });
  it('once a fallback channel is set, blocks without fallback account/template, and when fallback === primary', () => {
    expect(dcAddFormValid('SEND', { channel: 'WHATSAPP', account: 'x', templateId: 'CT-1', fallbackChannel: 'SMS', fallbackAccount: '', fallbackTemplateId: '' })).toBe(false);
    expect(dcAddFormValid('SEND', { channel: 'SMS', account: 'x', templateId: 'CT-1', fallbackChannel: 'SMS', fallbackAccount: 'x', fallbackTemplateId: 'CT-1' })).toBe(false);
    expect(dcAddFormValid('SEND', { channel: 'WHATSAPP', account: 'x', templateId: 'CT-1', fallbackChannel: 'SMS', fallbackAccount: 'x', fallbackTemplateId: 'CT-1' })).toBe(true);
  });
});

describe('Edit round-trip', () => {
  it('editing a Send name/channel never disturbs its auto Split/GOAL_EXIT subtree', () => {
    let g = addEntryEvent(EMPTY_GRAPH);
    const sendP = { ...dcDefaultConfig('SEND', null), name: 'Original', channel: 'WHATSAPP', account: 'IBL-Karix-Onb', templateId: 'CT-3310' };
    g = dcConfirmAddNode(g, 'SEND', sendP, { kind: 'growLeaf', nodeId: g.rootId! }, null);
    const before = Object.keys(g.nodes).length;
    const send = Object.values(g.nodes).find((n) => n.label === 'Original')!;
    const editedP = { ...send._config, name: 'Renamed' };
    g = dcConfirmEditNode(g, send.id, 'SEND', editedP, null);
    expect(Object.keys(g.nodes).length).toBe(before);
    expect(Object.values(g.nodes).some((n) => n.label === 'Renamed')).toBe(true);
    expect(Object.values(g.nodes).some((n) => n.label === 'Original')).toBe(false);
  });
});

describe('Branch insert/remove — the real data-integrity bug this reducer fixes', () => {
  it('inserting a branch mid-edit preserves every existing branch subtree and positions the new branch correctly', () => {
    let g = addEntryEvent(EMPTY_GRAPH);
    const p = {
      name: 'Decision', source: 'Account attribute', attribute: 'Milestone Progress %', outcome: 'Clicked',
      branches: [
        { id: 'b1', label: 'Branch 1', operator: 'Equals', value: '10', value2: '' },
        { id: 'b2', label: 'Branch 2', operator: 'Equals', value: '20', value2: '' },
      ],
    };
    g = dcConfirmAddNode(g, 'DECISION_SPLIT', p, { kind: 'growLeaf', nodeId: g.rootId! }, null);
    const ds = Object.values(g.nodes).find((n) => n.type === 'DECISION_SPLIT')!;
    const [edge0] = g.edges.filter((e) => e.from === ds.id);
    g = dcConfirmAddNode(g, 'EXIT', { reason: 'branch1 exit' }, { kind: 'edge', edgeId: edge0.id }, null);

    // Insert a new Branch 3 between Branch 1 and Branch 2.
    const editedP = {
      ...ds._config,
      branches: [p.branches[0], { id: 'b3', label: 'Branch 3', operator: 'Equals', value: '30', value2: '' }, p.branches[1]],
    };
    g = dcConfirmEditNode(g, ds.id, 'DECISION_SPLIT', editedP, null);

    const outs = g.edges.filter((e) => e.from === ds.id);
    expect(outs.length).toBe(4); // 3 branches + catch-all
    expect(outs.map((e) => e.branchLabel)).toEqual(['Branch 1 (10)', 'Branch 3 (30)', 'Branch 2 (20)', 'Anything else']);
    // Branch 1's subtree survived.
    const branch1Edge = outs.find((e) => e.branchLabel === 'Branch 1 (10)')!;
    expect(g.nodes[branch1Edge.to!]?.label).toBe('branch1 exit');
    // Branch 3 is a genuinely new open slot.
    const branch3Edge = outs.find((e) => e.branchLabel === 'Branch 3 (30)')!;
    expect(branch3Edge.to).toBeNull();
  });

  it('removing a branch cascade-GCs its subtree', () => {
    let g = addEntryEvent(EMPTY_GRAPH);
    const p = {
      name: 'Decision', source: 'Account attribute', attribute: 'Milestone Progress %', outcome: 'Clicked',
      branches: [
        { id: 'b1', label: 'Branch 1', operator: 'Equals', value: '10', value2: '' },
        { id: 'b2', label: 'Branch 2', operator: 'Equals', value: '20', value2: '' },
      ],
    };
    g = dcConfirmAddNode(g, 'DECISION_SPLIT', p, { kind: 'growLeaf', nodeId: g.rootId! }, null);
    const ds = Object.values(g.nodes).find((n) => n.type === 'DECISION_SPLIT')!;
    const [, edge1] = g.edges.filter((e) => e.from === ds.id);
    g = dcConfirmAddNode(g, 'EXIT', { reason: 'branch2 exit' }, { kind: 'edge', edgeId: edge1.id }, null);
    const beforeCount = Object.keys(g.nodes).length;

    const editedP = { ...ds._config, branches: [p.branches[0]] }; // remove Branch 2
    g = dcConfirmEditNode(g, ds.id, 'DECISION_SPLIT', editedP, null);

    expect(Object.keys(g.nodes).length).toBe(beforeCount - 1); // branch2's EXIT node gone
    expect(Object.values(g.nodes).some((n) => n.label === 'branch2 exit')).toBe(false);
    const outs = g.edges.filter((e) => e.from === ds.id);
    expect(outs.length).toBe(2); // 1 branch + catch-all
  });
});

describe('dcRemoveEdge', () => {
  it('reverts a Split branch to an open slot rather than deleting the edge', () => {
    let g = addEntryEvent(EMPTY_GRAPH);
    const p = { customSource: 'Account attribute', outcome: '', customConditions: [{ attribute: 'Status', operator: 'Equals', value: 'Active' }] };
    g = dcConfirmAddNode(g, 'SPLIT', p, { kind: 'growLeaf', nodeId: g.rootId! }, null);
    const split = Object.values(g.nodes).find((n) => n.type === 'SPLIT')!;
    const yesEdge = g.edges.find((e) => e.from === split.id && e.branchLabel === 'Yes')!;
    const beforeEdgeCount = g.edges.length;
    g = dcRemoveEdge(g, yesEdge.id);
    expect(g.edges.length).toBe(beforeEdgeCount); // edge stays, just reverted to open
    expect(g.edges.find((e) => e.id === yesEdge.id)!.to).toBeNull();
  });

  it('fully removes a plain growLeaf edge (no slot concept) and cascade-GCs its target', () => {
    let g = addEntryEvent(EMPTY_GRAPH);
    const sendP = { ...dcDefaultConfig('SEND', null), name: 'Msg1', channel: 'WHATSAPP', account: 'IBL-Karix-Onb', templateId: 'CT-3310' };
    g = dcConfirmAddNode(g, 'SEND', sendP, { kind: 'growLeaf', nodeId: g.rootId! }, null);
    const growEdge = g.edges.find((e) => e.from === g.rootId && e.branchLabel === '')!;
    g = dcRemoveEdge(g, growEdge.id);
    // Whole Send subtree (Send + its auto Split + auto GOAL_EXIT) cascade-removed.
    expect(Object.keys(g.nodes).length).toBe(1); // just the root Entry left
    expect(g.edges.length).toBe(0);
  });
});

describe('dcGraphHasOpenBranches validation', () => {
  it('a fresh Entry-only graph has open branches', () => {
    const g = addEntryEvent(EMPTY_GRAPH);
    expect(dcGraphHasOpenBranches(g)).toBe(true);
  });

  it('a fully resolved tree (every branch ends in GOAL_EXIT/EXIT) has none', () => {
    let g = addEntryEvent(EMPTY_GRAPH);
    g = dcConfirmAddNode(g, 'EXIT', { reason: 'done' }, { kind: 'growLeaf', nodeId: g.rootId! }, null);
    expect(dcGraphHasOpenBranches(g)).toBe(false);
  });
});
