// Ported scenario-for-scenario from this feature's original real-browser
// Playwright matrix (test_drip_full_matrix.js / test_drip_matrix_part2.js
// / verify_insert_branch.js, run against the plain-HTML prototype). Those
// scripts needed a real browser only because the logic lived inside
// onclick-string handlers mutating a global object — now that it's a pure
// reducer, the exact same scenarios run as fast, browser-free unit tests.
import { beforeEach, describe, expect, it } from 'vitest';
import type { DripGraph, DripGoal } from '../../src/data/graphTypes';
import { dcResetIdCounters } from '../../src/reducer/idGen';
import { dcValidMergeTargets, dcCanReach, dcGraphHasOpenBranches } from '../../src/reducer/graphOps';
import { dcConfirmAddNode, dcConfirmEditNode, dcRemoveEdge, dcConnectExisting, type DcAddingAt } from '../../src/reducer/campaignReducer';
import { dcDefaultConfig, dcAddFormValid } from '../../src/reducer/defaultConfig';

const EMPTY_GRAPH: DripGraph = { nodes: {}, edges: [], rootId: null };

function addEntryEvent(graph: DripGraph, overrides: Record<string, unknown> = {}): DripGraph {
  const p = { ...dcDefaultConfig('ENTRY_EVENT', null), eventCategory: 'Journey Events', eventType: 'Pageload', ...overrides };
  return dcConfirmAddNode(graph, 'ENTRY_EVENT', p, { kind: 'root' }, null);
}

beforeEach(() => {
  dcResetIdCounters();
});

describe('Entry nodes', () => {
  it('Entry Segment with a real condition', () => {
    const p = { ...dcDefaultConfig('ENTRY_SEGMENT', null), conditions: [{ attribute: 'Status', operator: 'Equals', value: 'Active' }] };
    const g = dcConfirmAddNode(EMPTY_GRAPH, 'ENTRY_SEGMENT', p, { kind: 'root' }, null);
    expect(g.rootId).toBeTruthy();
    const root = g.nodes[g.rootId!];
    expect(root.type).toBe('ENTRY_SEGMENT');
    expect(root.meta).toContain('Status = Active');
  });

  it('Entry Event sets the root', () => {
    const g = addEntryEvent(EMPTY_GRAPH);
    expect(g.rootId).toBeTruthy();
    expect(g.nodes[g.rootId!].type).toBe('ENTRY_EVENT');
  });

  it('Entry Scheduled with audience condition composes meta correctly', () => {
    const p = { ...dcDefaultConfig('ENTRY_SCHEDULED', null), entity: 'Account', conditions: [{ attribute: 'Status', operator: 'Equals', value: 'Active' }] };
    const g = dcConfirmAddNode(EMPTY_GRAPH, 'ENTRY_SCHEDULED', p, { kind: 'root' }, null);
    const root = g.nodes[g.rootId!];
    expect(root.meta).toContain('Account');
    expect(root.meta).not.toContain('undefined');
  });
});

describe('Send -> auto goal-check', () => {
  it('Send auto-inserts a Split + GOAL_EXIT, both resolve independently when chained with Channel Failover', () => {
    let g = addEntryEvent(EMPTY_GRAPH);
    const sendP = { ...dcDefaultConfig('SEND', null), name: 'Msg1', channel: 'WHATSAPP', account: 'IBL-Karix-Onb', templateId: 'CT-3310' };
    g = dcConfirmAddNode(g, 'SEND', sendP, { kind: 'growLeaf', nodeId: g.rootId! }, null);
    expect(Object.keys(g.nodes).length).toBeGreaterThanOrEqual(3); // Entry + Send + auto Split (+ GOAL_EXIT)

    const send = Object.values(g.nodes).find((n) => n.label === 'Msg1')!;
    const splitEdge = g.edges.find((e) => e.from === send.id)!;
    const split = g.nodes[splitEdge.to!];
    expect(split.type).toBe('SPLIT');
    expect(split.autoGenerated).toBe(false);
    const yesEdge = g.edges.find((e) => e.from === split.id && e.branchLabel === 'Yes')!;
    expect(g.nodes[yesEdge.to!].type).toBe('GOAL_EXIT');

    const noEdge = g.edges.find((e) => e.from === split.id && e.branchLabel === 'No')!;
    expect(noEdge.to).toBeNull();

    // chain Channel Failover under the No branch
    const cfP = { ...dcDefaultConfig('CHANNEL_FAILOVER', null), primaryChannel: 'WHATSAPP', fallbackChannel: 'SMS', account: 'IBL-Karix-Txns', templateId: 'CT-3301' };
    g = dcConfirmAddNode(g, 'CHANNEL_FAILOVER', cfP, { kind: 'edge', edgeId: noEdge.id }, null);
    const cfNode = Object.values(g.nodes).find((n) => n.type === 'CHANNEL_FAILOVER')!;
    const cfSplitEdge = g.edges.find((e) => e.from === cfNode.id)!;
    expect(g.nodes[cfSplitEdge.to!].type).toBe('SPLIT');
  });
});

describe('Pause', () => {
  it('Pause gets its own auto goal-check Split', () => {
    let g = addEntryEvent(EMPTY_GRAPH);
    g = dcConfirmAddNode(g, 'PAUSE', { duration: 3, unit: 'days' }, { kind: 'growLeaf', nodeId: g.rootId! }, null);
    const pause = Object.values(g.nodes).find((n) => n.type === 'PAUSE')!;
    const edge = g.edges.find((e) => e.from === pause.id)!;
    expect(g.nodes[edge.to!].type).toBe('SPLIT');
  });
});

describe('Wait Until', () => {
  const goal: DripGoal = { eventCategory: 'EMI Events', eventType: 'EMI_STATUS_CHANGED', conditions: [{ attribute: 'New Status', operator: 'Equals', value: 'Successful' }] };

  it('promoted attribute matching the campaign Goal -> real outcome-check Split', () => {
    let g = addEntryEvent(EMPTY_GRAPH, { eventCategory: 'Transaction Events', eventType: 'Transaction' });
    const p = { eventCategory: 'EMI Events', eventType: 'EMI_STATUS_CHANGED', duration: 7, unit: 'days', conditions: [] };
    g = dcConfirmAddNode(g, 'WAIT_UNTIL', p, { kind: 'growLeaf', nodeId: g.rootId! }, goal);
    const wu = Object.values(g.nodes).find((n) => n.type === 'WAIT_UNTIL')!;
    const toSplitEdge = g.edges.find((e) => e.from === wu.id && e.branchLabel === '')!;
    const split = g.nodes[toSplitEdge.to!];
    expect(split.type).toBe('SPLIT');
    const yes = g.edges.find((e) => e.from === split.id && e.branchLabel === 'Yes')!;
    const no = g.edges.find((e) => e.from === split.id && e.branchLabel === 'No')!;
    expect(g.nodes[yes.to!].type).toBe('GOAL_EXIT');
    expect(g.nodes[no.to!].type).toBe('EXIT');
  });

  it('unambiguous event (no promoted attribute) -> direct Yes -> GOAL_EXIT', () => {
    let g = addEntryEvent(EMPTY_GRAPH);
    const p = { eventCategory: 'Journey Events', eventType: 'Journey Progress', duration: 10, unit: 'days', conditions: [] };
    g = dcConfirmAddNode(g, 'WAIT_UNTIL', p, { kind: 'growLeaf', nodeId: g.rootId! }, null);
    const wu = Object.values(g.nodes).find((n) => n.type === 'WAIT_UNTIL')!;
    const yes = g.edges.find((e) => e.from === wu.id && e.branchLabel === 'Yes')!;
    expect(g.nodes[yes.to!].type).toBe('GOAL_EXIT');
  });

  it('promoted attribute NOT matching the campaign Goal -> both branches open, no guess', () => {
    const otherGoal: DripGoal = { eventCategory: 'Journey Events', eventType: 'Journey Progress', conditions: [] };
    let g = addEntryEvent(EMPTY_GRAPH, { eventCategory: 'Transaction Events', eventType: 'Transaction' });
    const p = { eventCategory: 'EMI Events', eventType: 'EMI_STATUS_CHANGED', duration: 5, unit: 'days', conditions: [] };
    g = dcConfirmAddNode(g, 'WAIT_UNTIL', p, { kind: 'growLeaf', nodeId: g.rootId! }, otherGoal);
    const wu = Object.values(g.nodes).find((n) => n.type === 'WAIT_UNTIL')!;
    const toSplitEdge = g.edges.find((e) => e.from === wu.id && e.branchLabel === '')!;
    const split = g.nodes[toSplitEdge.to!];
    const openEdges = g.edges.filter((e) => e.from === split.id && e.to === null);
    expect(openEdges.length).toBe(2);
  });
});

describe('Split', () => {
  it('Goal reached basis reflects the real campaign goal, locked', () => {
    const goal: DripGoal = { eventCategory: 'EMI Events', eventType: 'EMI_STATUS_CHANGED', conditions: [{ attribute: 'New Status', operator: 'Equals', value: 'Successful' }] };
    let g = addEntryEvent(EMPTY_GRAPH);
    const p = { basis: 'Goal reached', customSource: 'Previous step outcome', outcome: 'Clicked', customConditions: [] };
    g = dcConfirmAddNode(g, 'SPLIT', p, { kind: 'growLeaf', nodeId: g.rootId! }, goal);
    const split = Object.values(g.nodes).find((n) => n.type === 'SPLIT')!;
    expect(split.label).toContain('EMI_STATUS_CHANGED');
  });

  it('Custom condition split (Account attribute) builds a real Yes/No pair', () => {
    let g = addEntryEvent(EMPTY_GRAPH);
    const p = { basis: 'Custom condition', customSource: 'Account attribute', outcome: '', customConditions: [{ attribute: 'Engagement Tier', operator: 'Any of', values: ['Dormant'] }] };
    g = dcConfirmAddNode(g, 'SPLIT', p, { kind: 'growLeaf', nodeId: g.rootId! }, null);
    const split = Object.values(g.nodes).find((n) => n.meta === 'Custom condition split')!;
    expect(split).toBeTruthy();
    expect(g.edges.some((e) => e.from === split.id && e.branchLabel === 'Yes')).toBe(true);
    expect(g.edges.some((e) => e.from === split.id && e.branchLabel === 'No')).toBe(true);
  });
});

describe('Decision Split', () => {
  it('2 branches + catch-all, correct summary labels', () => {
    let g = addEntryEvent(EMPTY_GRAPH);
    const p = {
      name: 'Decision', source: 'Account attribute', attribute: 'Milestone Progress %', outcome: 'Clicked',
      branches: [
        { id: 'b1', label: 'Branch 1', operator: 'Between', value: '5', value2: '20' },
        { id: 'b2', label: 'Branch 2', operator: 'Between', value: '21', value2: '50' },
      ],
    };
    g = dcConfirmAddNode(g, 'DECISION_SPLIT', p, { kind: 'growLeaf', nodeId: g.rootId! }, null);
    const ds = Object.values(g.nodes).find((n) => n.type === 'DECISION_SPLIT')!;
    expect(ds.label).toBe('Milestone Progress %');
    expect(ds.meta).toBe('2 branches + catch-all');
    const labels = g.edges.filter((e) => e.from === ds.id).map((e) => e.branchLabel);
    expect(labels).toEqual(['Branch 1 (5–20)', 'Branch 2 (21–50)', 'Anything else']);
  });

  it('dcAddFormValid blocks when a branch value is missing', () => {
    const p = { ...dcDefaultConfig('DECISION_SPLIT', null), attribute: 'Milestone Progress %' };
    expect(dcAddFormValid('DECISION_SPLIT', p)).toBe(false); // branch values empty by default
  });
});

describe('Random Split', () => {
  it('N branches become N open edges', () => {
    let g = addEntryEvent(EMPTY_GRAPH);
    const p = { name: 'Channel test', branches: [{ id: 'a', label: 'A', pct: 34 }, { id: 'b', label: 'B', pct: 33 }, { id: 'c', label: 'C', pct: 33 }] };
    g = dcConfirmAddNode(g, 'RANDOM_SPLIT', p, { kind: 'growLeaf', nodeId: g.rootId! }, null);
    const rs = Object.values(g.nodes).find((n) => n.type === 'RANDOM_SPLIT')!;
    expect(g.edges.filter((e) => e.from === rs.id).length).toBe(3);
  });

  it('dcAddFormValid requires percentages to sum to 100', () => {
    const p = { branches: [{ pct: 30 }, { pct: 30 }] };
    expect(dcAddFormValid('RANDOM_SPLIT', p)).toBe(false);
    expect(dcAddFormValid('RANDOM_SPLIT', { branches: [{ pct: 60 }, { pct: 40 }] })).toBe(true);
  });
});

describe('Channel Failover validation', () => {
  it('blocks without account/template, and when primary === fallback', () => {
    expect(dcAddFormValid('CHANNEL_FAILOVER', { primaryChannel: 'WHATSAPP', fallbackChannel: 'SMS', account: '', templateId: '' })).toBe(false);
    expect(dcAddFormValid('CHANNEL_FAILOVER', { primaryChannel: 'SMS', fallbackChannel: 'SMS', account: 'x', templateId: 'CT-1' })).toBe(false);
    expect(dcAddFormValid('CHANNEL_FAILOVER', { primaryChannel: 'WHATSAPP', fallbackChannel: 'SMS', account: 'x', templateId: 'CT-1' })).toBe(true);
  });
});

describe('Edit round-trip', () => {
  it('editing a Send name/channel never disturbs its auto Split/GOAL_EXIT subtree', () => {
    let g = addEntryEvent(EMPTY_GRAPH);
    const sendP = { ...dcDefaultConfig('SEND', null), name: 'Original', channel: 'WHATSAPP', account: 'IBL-Karix-Onb', templateId: 'CT-3310' };
    g = dcConfirmAddNode(g, 'SEND', sendP, { kind: 'growLeaf', nodeId: g.rootId! }, null);
    const before = Object.keys(g.nodes).length;
    const send = Object.values(g.nodes).find((n) => n.label === 'Original')!;
    const editedP = { ...send._config, name: 'Renamed' };
    g = dcConfirmEditNode(g, send.id, 'SEND', editedP, null);
    expect(Object.keys(g.nodes).length).toBe(before);
    expect(Object.values(g.nodes).some((n) => n.label === 'Renamed')).toBe(true);
    expect(Object.values(g.nodes).some((n) => n.label === 'Original')).toBe(false);
  });
});

describe('Branch insert/remove — the real data-integrity bug this reducer fixes', () => {
  it('inserting a branch mid-edit preserves every existing branch subtree and positions the new branch correctly', () => {
    let g = addEntryEvent(EMPTY_GRAPH);
    const p = {
      name: 'Decision', source: 'Account attribute', attribute: 'Milestone Progress %', outcome: 'Clicked',
      branches: [
        { id: 'b1', label: 'Branch 1', operator: 'Equals', value: '10', value2: '' },
        { id: 'b2', label: 'Branch 2', operator: 'Equals', value: '20', value2: '' },
      ],
    };
    g = dcConfirmAddNode(g, 'DECISION_SPLIT', p, { kind: 'growLeaf', nodeId: g.rootId! }, null);
    const ds = Object.values(g.nodes).find((n) => n.type === 'DECISION_SPLIT')!;
    const [edge0] = g.edges.filter((e) => e.from === ds.id);
    g = dcConfirmAddNode(g, 'EXIT', { reason: 'branch1 exit' }, { kind: 'edge', edgeId: edge0.id }, null);

    // Insert a new Branch 3 between Branch 1 and Branch 2.
    const editedP = {
      ...ds._config,
      branches: [p.branches[0], { id: 'b3', label: 'Branch 3', operator: 'Equals', value: '30', value2: '' }, p.branches[1]],
    };
    g = dcConfirmEditNode(g, ds.id, 'DECISION_SPLIT', editedP, null);

    const outs = g.edges.filter((e) => e.from === ds.id);
    expect(outs.length).toBe(4); // 3 branches + catch-all
    expect(outs.map((e) => e.branchLabel)).toEqual(['Branch 1 (10)', 'Branch 3 (30)', 'Branch 2 (20)', 'Anything else']);
    // Branch 1's subtree survived.
    const branch1Edge = outs.find((e) => e.branchLabel === 'Branch 1 (10)')!;
    expect(g.nodes[branch1Edge.to!]?.label).toBe('branch1 exit');
    // Branch 3 is a genuinely new open slot.
    const branch3Edge = outs.find((e) => e.branchLabel === 'Branch 3 (30)')!;
    expect(branch3Edge.to).toBeNull();
  });

  it('removing a branch cascade-GCs its subtree', () => {
    let g = addEntryEvent(EMPTY_GRAPH);
    const p = {
      name: 'Decision', source: 'Account attribute', attribute: 'Milestone Progress %', outcome: 'Clicked',
      branches: [
        { id: 'b1', label: 'Branch 1', operator: 'Equals', value: '10', value2: '' },
        { id: 'b2', label: 'Branch 2', operator: 'Equals', value: '20', value2: '' },
      ],
    };
    g = dcConfirmAddNode(g, 'DECISION_SPLIT', p, { kind: 'growLeaf', nodeId: g.rootId! }, null);
    const ds = Object.values(g.nodes).find((n) => n.type === 'DECISION_SPLIT')!;
    const [, edge1] = g.edges.filter((e) => e.from === ds.id);
    g = dcConfirmAddNode(g, 'EXIT', { reason: 'branch2 exit' }, { kind: 'edge', edgeId: edge1.id }, null);
    const beforeCount = Object.keys(g.nodes).length;

    const editedP = { ...ds._config, branches: [p.branches[0]] }; // remove Branch 2
    g = dcConfirmEditNode(g, ds.id, 'DECISION_SPLIT', editedP, null);

    expect(Object.keys(g.nodes).length).toBe(beforeCount - 1); // branch2's EXIT node gone
    expect(Object.values(g.nodes).some((n) => n.label === 'branch2 exit')).toBe(false);
    const outs = g.edges.filter((e) => e.from === ds.id);
    expect(outs.length).toBe(2); // 1 branch + catch-all
  });
});

describe('Cycle prevention', () => {
  it('a node cannot merge into itself or its own ancestor', () => {
    let g = addEntryEvent(EMPTY_GRAPH);
    const sendP = { ...dcDefaultConfig('SEND', null), name: 'Msg1', channel: 'WHATSAPP', account: 'IBL-Karix-Onb', templateId: 'CT-3310' };
    g = dcConfirmAddNode(g, 'SEND', sendP, { kind: 'growLeaf', nodeId: g.rootId! }, null);
    const entryId = g.rootId!;
    const send = Object.values(g.nodes).find((n) => n.label === 'Msg1')!;
    const targets = dcValidMergeTargets(g, send.id).map((n) => n.id);
    expect(targets).not.toContain(send.id); // not itself
    expect(targets).not.toContain(entryId); // not its own ancestor
    expect(dcCanReach(g, entryId, send.id)).toBe(true);
    expect(dcCanReach(g, send.id, entryId)).toBe(false);
  });
});

describe('dcRemoveEdge', () => {
  it('reverts a Split branch to an open slot rather than deleting the edge', () => {
    let g = addEntryEvent(EMPTY_GRAPH);
    const p = { basis: 'Custom condition', customSource: 'Account attribute', outcome: '', customConditions: [{ attribute: 'Status', operator: 'Equals', value: 'Active' }] };
    g = dcConfirmAddNode(g, 'SPLIT', p, { kind: 'growLeaf', nodeId: g.rootId! }, null);
    const split = Object.values(g.nodes).find((n) => n.type === 'SPLIT')!;
    const yesEdge = g.edges.find((e) => e.from === split.id && e.branchLabel === 'Yes')!;
    const beforeEdgeCount = g.edges.length;
    g = dcRemoveEdge(g, yesEdge.id);
    expect(g.edges.length).toBe(beforeEdgeCount); // edge stays, just reverted to open
    expect(g.edges.find((e) => e.id === yesEdge.id)!.to).toBeNull();
  });

  it('fully removes a plain growLeaf edge (no slot concept) and cascade-GCs its target', () => {
    let g = addEntryEvent(EMPTY_GRAPH);
    const sendP = { ...dcDefaultConfig('SEND', null), name: 'Msg1', channel: 'WHATSAPP', account: 'IBL-Karix-Onb', templateId: 'CT-3310' };
    g = dcConfirmAddNode(g, 'SEND', sendP, { kind: 'growLeaf', nodeId: g.rootId! }, null);
    const growEdge = g.edges.find((e) => e.from === g.rootId && e.branchLabel === '')!;
    g = dcRemoveEdge(g, growEdge.id);
    // Whole Send subtree (Send + its auto Split + auto GOAL_EXIT) cascade-removed.
    expect(Object.keys(g.nodes).length).toBe(1); // just the root Entry left
    expect(g.edges.length).toBe(0);
  });
});

describe('dcGraphHasOpenBranches validation', () => {
  it('a fresh Entry-only graph has open branches', () => {
    const g = addEntryEvent(EMPTY_GRAPH);
    expect(dcGraphHasOpenBranches(g)).toBe(true);
  });

  it('a fully resolved tree (every branch ends in GOAL_EXIT/EXIT) has none', () => {
    let g = addEntryEvent(EMPTY_GRAPH);
    g = dcConfirmAddNode(g, 'EXIT', { reason: 'done' }, { kind: 'growLeaf', nodeId: g.rootId! }, null);
    expect(dcGraphHasOpenBranches(g)).toBe(false);
  });
});

describe('Connect to an existing step', () => {
  it('merging into an existing node adds one edge, creates no new node', () => {
    let g = addEntryEvent(EMPTY_GRAPH);
    const sendP = { ...dcDefaultConfig('SEND', null), name: 'Shared', channel: 'WHATSAPP', account: 'IBL-Karix-Onb', templateId: 'CT-3310' };
    g = dcConfirmAddNode(g, 'SEND', sendP, { kind: 'growLeaf', nodeId: g.rootId! }, null);
    const shared = Object.values(g.nodes).find((n) => n.label === 'Shared')!;
    const send = Object.values(g.nodes).find((n) => n.type === 'SPLIT')!;
    const noEdge = g.edges.find((e) => e.from === send.id && e.branchLabel === 'No')!;
    const beforeNodeCount = Object.keys(g.nodes).length;
    g = dcConnectExisting(g, { kind: 'edge', edgeId: noEdge.id }, shared.id);
    expect(Object.keys(g.nodes).length).toBe(beforeNodeCount); // no new node
    expect(g.edges.filter((e) => e.to === shared.id).length).toBe(2); // now reached from 2 places
  });
});
