// Core graph shape, ported from journeysnudgesemi/emi-conversions-prototype.html
// (the 2026-09-25 graph rebuild) — already id/edge-based, not the older
// nested-children tree. Porting means field-name adaptation (`from`/`to`
// stay as-is here; React Flow's own `source`/`target` naming is applied
// only at the render-layer adapter, not in this canonical shape) and
// moving mutation from a global object to a reducer, not a structural
// redesign.

import type { DcNodeType } from './nodeMeta';

export interface DripNode {
  id: string;
  type: DcNodeType;
  label: string;
  meta: string;
  autoGenerated: boolean;
  // Raw pendingConfig snapshot from whichever drawer form built/last-edited
  // this node — absent on nodes that predate this concept (all 6 ported
  // seed campaigns): opening one of those for Edit shows blank fields, a
  // known, pre-existing limitation carried over as-is, not newly
  // introduced by this port.
  _config?: Record<string, unknown> | null;
}

export interface DripEdge {
  id: string;
  from: string;
  // null = an open slot ("+" add-step button), not yet connected to a node.
  to: string | null;
  branchLabel: string;
  autoGenerated: boolean;
  // Stable branch identity for Random Split / Decision Split branches —
  // lets an edit that inserts/removes a branch reconcile by identity
  // instead of fragile array-position/count matching. Absent on edges
  // that predate this (legacy branches); the reducer backfills it lazily,
  // same behavior as the original.
  branchId?: string;
}

export interface DripGraph {
  nodes: Record<string, DripNode>;
  edges: DripEdge[];
  rootId: string | null;
}

export interface DripGoalCondition {
  attribute: string;
  operator: string;
  value?: string;
  values?: string[];
  value2?: string;
}

export interface DripGoal {
  eventCategory: string;
  eventType: string;
  conditions: DripGoalCondition[];
}

export type DripCampaignStatus =
  | 'DRAFT' | 'PENDING_REVIEW' | 'ACTIVE' | 'SCHEDULED' | 'PAUSED' | 'KILLED' | 'CHANGES_REQUESTED';

export interface DripCampaign {
  id: string;
  name: string;
  description?: string;
  issuer: string;
  programs: string[];
  goal: DripGoal | null;
  controlPct: number;
  status: DripCampaignStatus;
  root: DripGraph | null;
  startDate?: string;
  endDate?: string;
  versionOf?: string | null;
}
