// Ported from journeysnudgesemi/emi-conversions-prototype.html @ 2026-09-25.
// Extracted directly from the running prototype (DRIP_CAMPAIGNS, already
// converted from its nested seed-tree literal into real {nodes, edges,
// rootId} graph shape) rather than hand-retyped — avoids re-porting the
// tree->graph conversion logic for data that only needs to exist once.
// One-time fork, not a live shared source — see sharedConstants.ts.
import type { DripCampaign } from './graphTypes';

export const DRIP_CAMPAIGNS: DripCampaign[] = [
  {
    "id": "DRIP-001",
    "name": "Card Activation Reminder",
    "issuer": "IndusInd Bank (IBL)",
    "programs": [],
    "goal": {
      "eventCategory": "Card Events",
      "eventType": "Card Activated",
      "conditions": []
    },
    "controlPct": 10,
    "status": "ACTIVE",
    "root": {
      "nodes": {
        "dcn1": {
          "id": "dcn1",
          "type": "ENTRY_EVENT",
          "label": "Card Issued",
          "meta": "Card Events · fires on issuance",
          "autoGenerated": false
        },
        "dcn2": {
          "id": "dcn2",
          "type": "SEND",
          "label": "Welcome + Activate CTA",
          "meta": "WhatsApp · 11:00 AM · Template: card_activate_welcome",
          "autoGenerated": false
        },
        "dcn3": {
          "id": "dcn3",
          "type": "SPLIT",
          "label": "Card Activated?",
          "meta": "Goal check, auto-inserted after every Send",
          "autoGenerated": false
        },
        "dcn4": {
          "id": "dcn4",
          "type": "GOAL_EXIT",
          "label": "Activated",
          "meta": "",
          "autoGenerated": false
        },
        "dcn5": {
          "id": "dcn5",
          "type": "PAUSE",
          "label": "Wait 3 days",
          "meta": "",
          "autoGenerated": false
        },
        "dcn6": {
          "id": "dcn6",
          "type": "SEND",
          "label": "Reminder 2",
          "meta": "SMS · Relative · Template: card_activate_reminder2",
          "autoGenerated": false
        },
        "dcn7": {
          "id": "dcn7",
          "type": "SPLIT",
          "label": "Card Activated?",
          "meta": "",
          "autoGenerated": false
        },
        "dcn8": {
          "id": "dcn8",
          "type": "GOAL_EXIT",
          "label": "Activated",
          "meta": "",
          "autoGenerated": false
        },
        "dcn9": {
          "id": "dcn9",
          "type": "PAUSE",
          "label": "Wait 4 days",
          "meta": "",
          "autoGenerated": false
        },
        "dcn10": {
          "id": "dcn10",
          "type": "SEND",
          "label": "Final reminder",
          "meta": "WhatsApp · Relative · Template: card_activate_final",
          "autoGenerated": false
        },
        "dcn11": {
          "id": "dcn11",
          "type": "SPLIT",
          "label": "Card Activated?",
          "meta": "",
          "autoGenerated": false
        },
        "dcn12": {
          "id": "dcn12",
          "type": "GOAL_EXIT",
          "label": "Activated",
          "meta": "",
          "autoGenerated": false
        },
        "dcn13": {
          "id": "dcn13",
          "type": "EXIT",
          "label": "Sequence exhausted",
          "meta": "No activation after 3 attempts",
          "autoGenerated": false
        }
      },
      "edges": [
        {
          "id": "dce1",
          "from": "dcn3",
          "to": "dcn4",
          "branchLabel": "Yes",
          "autoGenerated": false
        },
        {
          "id": "dce2",
          "from": "dcn7",
          "to": "dcn8",
          "branchLabel": "Yes",
          "autoGenerated": false
        },
        {
          "id": "dce3",
          "from": "dcn11",
          "to": "dcn12",
          "branchLabel": "Yes",
          "autoGenerated": false
        },
        {
          "id": "dce4",
          "from": "dcn11",
          "to": "dcn13",
          "branchLabel": "No",
          "autoGenerated": false
        },
        {
          "id": "dce5",
          "from": "dcn10",
          "to": "dcn11",
          "branchLabel": "",
          "autoGenerated": false
        },
        {
          "id": "dce6",
          "from": "dcn9",
          "to": "dcn10",
          "branchLabel": "",
          "autoGenerated": false
        },
        {
          "id": "dce7",
          "from": "dcn7",
          "to": "dcn9",
          "branchLabel": "No",
          "autoGenerated": false
        },
        {
          "id": "dce8",
          "from": "dcn6",
          "to": "dcn7",
          "branchLabel": "",
          "autoGenerated": false
        },
        {
          "id": "dce9",
          "from": "dcn5",
          "to": "dcn6",
          "branchLabel": "",
          "autoGenerated": false
        },
        {
          "id": "dce10",
          "from": "dcn3",
          "to": "dcn5",
          "branchLabel": "No",
          "autoGenerated": false
        },
        {
          "id": "dce11",
          "from": "dcn2",
          "to": "dcn3",
          "branchLabel": "",
          "autoGenerated": false
        },
        {
          "id": "dce12",
          "from": "dcn1",
          "to": "dcn2",
          "branchLabel": "",
          "autoGenerated": false
        }
      ],
      "rootId": "dcn1"
    }
  },
  {
    "id": "DRIP-002",
    "name": "OS to EMI — Reminder Push",
    "issuer": "IndusInd Bank (IBL)",
    "programs": [],
    "goal": {
      "eventCategory": "EMI Events",
      "eventType": "EMI_STATUS_CHANGED",
      "conditions": [
        {
          "attribute": "New Status",
          "operator": "Equals",
          "value": "Successful"
        }
      ]
    },
    "controlPct": 10,
    "status": "ACTIVE",
    "root": {
      "nodes": {
        "dcn14": {
          "id": "dcn14",
          "type": "ENTRY_SEGMENT",
          "label": "All Eligible Customers",
          "meta": "OS > ₹5,000 · Card Events",
          "autoGenerated": false
        },
        "dcn15": {
          "id": "dcn15",
          "type": "RANDOM_SPLIT",
          "label": "Channel test",
          "meta": "50 / 50 allocation",
          "autoGenerated": false
        },
        "dcn16": {
          "id": "dcn16",
          "type": "SEND",
          "label": "OS to EMI Offer",
          "meta": "WhatsApp · 11:00 AM · Template: os_emi_offer_wa",
          "autoGenerated": false
        },
        "dcn17": {
          "id": "dcn17",
          "type": "SPLIT",
          "label": "Converted to EMI?",
          "meta": "",
          "autoGenerated": false
        },
        "dcn18": {
          "id": "dcn18",
          "type": "GOAL_EXIT",
          "label": "Converted",
          "meta": "",
          "autoGenerated": false
        },
        "dcn19": {
          "id": "dcn19",
          "type": "PAUSE",
          "label": "Wait 2 days",
          "meta": "",
          "autoGenerated": false
        },
        "dcn20": {
          "id": "dcn20",
          "type": "SEND",
          "label": "Reminder",
          "meta": "WhatsApp · Relative · Template: os_emi_reminder_wa",
          "autoGenerated": false
        },
        "dcn21": {
          "id": "dcn21",
          "type": "SPLIT",
          "label": "Converted to EMI?",
          "meta": "",
          "autoGenerated": false
        },
        "dcn22": {
          "id": "dcn22",
          "type": "GOAL_EXIT",
          "label": "Converted",
          "meta": "",
          "autoGenerated": false
        },
        "dcn23": {
          "id": "dcn23",
          "type": "EXIT",
          "label": "Sequence exhausted",
          "meta": "",
          "autoGenerated": false
        },
        "dcn24": {
          "id": "dcn24",
          "type": "SEND",
          "label": "OS to EMI Offer",
          "meta": "SMS · 11:00 AM · Template: os_emi_offer_sms",
          "autoGenerated": false
        },
        "dcn25": {
          "id": "dcn25",
          "type": "SPLIT",
          "label": "Converted to EMI?",
          "meta": "",
          "autoGenerated": false
        },
        "dcn26": {
          "id": "dcn26",
          "type": "GOAL_EXIT",
          "label": "Converted",
          "meta": "",
          "autoGenerated": false
        },
        "dcn27": {
          "id": "dcn27",
          "type": "PAUSE",
          "label": "Wait 2 days",
          "meta": "",
          "autoGenerated": false
        },
        "dcn28": {
          "id": "dcn28",
          "type": "SEND",
          "label": "Reminder",
          "meta": "SMS · Relative · Template: os_emi_reminder_sms",
          "autoGenerated": false
        },
        "dcn29": {
          "id": "dcn29",
          "type": "SPLIT",
          "label": "Converted to EMI?",
          "meta": "",
          "autoGenerated": false
        },
        "dcn30": {
          "id": "dcn30",
          "type": "GOAL_EXIT",
          "label": "Converted",
          "meta": "",
          "autoGenerated": false
        },
        "dcn31": {
          "id": "dcn31",
          "type": "EXIT",
          "label": "Sequence exhausted",
          "meta": "",
          "autoGenerated": false
        }
      },
      "edges": [
        {
          "id": "dce13",
          "from": "dcn17",
          "to": "dcn18",
          "branchLabel": "Yes",
          "autoGenerated": false
        },
        {
          "id": "dce14",
          "from": "dcn21",
          "to": "dcn22",
          "branchLabel": "Yes",
          "autoGenerated": false
        },
        {
          "id": "dce15",
          "from": "dcn21",
          "to": "dcn23",
          "branchLabel": "No",
          "autoGenerated": false
        },
        {
          "id": "dce16",
          "from": "dcn20",
          "to": "dcn21",
          "branchLabel": "",
          "autoGenerated": false
        },
        {
          "id": "dce17",
          "from": "dcn19",
          "to": "dcn20",
          "branchLabel": "",
          "autoGenerated": false
        },
        {
          "id": "dce18",
          "from": "dcn17",
          "to": "dcn19",
          "branchLabel": "No",
          "autoGenerated": false
        },
        {
          "id": "dce19",
          "from": "dcn16",
          "to": "dcn17",
          "branchLabel": "",
          "autoGenerated": false
        },
        {
          "id": "dce20",
          "from": "dcn15",
          "to": "dcn16",
          "branchLabel": "50% WhatsApp",
          "autoGenerated": false
        },
        {
          "id": "dce21",
          "from": "dcn25",
          "to": "dcn26",
          "branchLabel": "Yes",
          "autoGenerated": false
        },
        {
          "id": "dce22",
          "from": "dcn29",
          "to": "dcn30",
          "branchLabel": "Yes",
          "autoGenerated": false
        },
        {
          "id": "dce23",
          "from": "dcn29",
          "to": "dcn31",
          "branchLabel": "No",
          "autoGenerated": false
        },
        {
          "id": "dce24",
          "from": "dcn28",
          "to": "dcn29",
          "branchLabel": "",
          "autoGenerated": false
        },
        {
          "id": "dce25",
          "from": "dcn27",
          "to": "dcn28",
          "branchLabel": "",
          "autoGenerated": false
        },
        {
          "id": "dce26",
          "from": "dcn25",
          "to": "dcn27",
          "branchLabel": "No",
          "autoGenerated": false
        },
        {
          "id": "dce27",
          "from": "dcn24",
          "to": "dcn25",
          "branchLabel": "",
          "autoGenerated": false
        },
        {
          "id": "dce28",
          "from": "dcn15",
          "to": "dcn24",
          "branchLabel": "50% SMS",
          "autoGenerated": false
        },
        {
          "id": "dce29",
          "from": "dcn14",
          "to": "dcn15",
          "branchLabel": "",
          "autoGenerated": false
        }
      ],
      "rootId": "dcn14"
    }
  },
  {
    "id": "DRIP-003",
    "name": "Spend Milestone Rewards",
    "issuer": "Yes Bank",
    "programs": [],
    "goal": null,
    "controlPct": 0,
    "status": "DRAFT",
    "root": {
      "nodes": {
        "dcn32": {
          "id": "dcn32",
          "type": "ENTRY_EVENT",
          "label": "Card Activated",
          "meta": "Card Events · anchor for every checkpoint below",
          "autoGenerated": false
        },
        "dcn33": {
          "id": "dcn33",
          "type": "PAUSE",
          "label": "Wait 30 days",
          "meta": "",
          "autoGenerated": false
        },
        "dcn34": {
          "id": "dcn34",
          "type": "SEND",
          "label": "Milestone reward — Tier 1",
          "meta": "WhatsApp · Template: milestone_m1",
          "autoGenerated": false
        },
        "dcn35": {
          "id": "dcn35",
          "type": "EXIT",
          "label": "Checkpoint complete",
          "meta": "",
          "autoGenerated": false
        },
        "dcn36": {
          "id": "dcn36",
          "type": "PAUSE",
          "label": "Wait 90 days",
          "meta": "",
          "autoGenerated": false
        },
        "dcn37": {
          "id": "dcn37",
          "type": "SEND",
          "label": "Milestone reward — Tier 2",
          "meta": "WhatsApp · Template: milestone_m3",
          "autoGenerated": false
        },
        "dcn38": {
          "id": "dcn38",
          "type": "EXIT",
          "label": "Checkpoint complete",
          "meta": "",
          "autoGenerated": false
        },
        "dcn39": {
          "id": "dcn39",
          "type": "PAUSE",
          "label": "Wait 180 days",
          "meta": "",
          "autoGenerated": false
        },
        "dcn40": {
          "id": "dcn40",
          "type": "SEND",
          "label": "Milestone reward — Tier 3",
          "meta": "WhatsApp · Template: milestone_m6",
          "autoGenerated": false
        },
        "dcn41": {
          "id": "dcn41",
          "type": "EXIT",
          "label": "Checkpoint complete",
          "meta": "",
          "autoGenerated": false
        },
        "dcn42": {
          "id": "dcn42",
          "type": "PAUSE",
          "label": "Wait 365 days",
          "meta": "",
          "autoGenerated": false
        },
        "dcn43": {
          "id": "dcn43",
          "type": "SEND",
          "label": "Milestone reward — Tier 4",
          "meta": "WhatsApp · Template: milestone_m12",
          "autoGenerated": false
        },
        "dcn44": {
          "id": "dcn44",
          "type": "EXIT",
          "label": "Checkpoint complete",
          "meta": "",
          "autoGenerated": false
        }
      },
      "edges": [
        {
          "id": "dce30",
          "from": "dcn34",
          "to": "dcn35",
          "branchLabel": "",
          "autoGenerated": false
        },
        {
          "id": "dce31",
          "from": "dcn33",
          "to": "dcn34",
          "branchLabel": "",
          "autoGenerated": false
        },
        {
          "id": "dce32",
          "from": "dcn32",
          "to": "dcn33",
          "branchLabel": "Month 1",
          "autoGenerated": false
        },
        {
          "id": "dce33",
          "from": "dcn37",
          "to": "dcn38",
          "branchLabel": "",
          "autoGenerated": false
        },
        {
          "id": "dce34",
          "from": "dcn36",
          "to": "dcn37",
          "branchLabel": "",
          "autoGenerated": false
        },
        {
          "id": "dce35",
          "from": "dcn32",
          "to": "dcn36",
          "branchLabel": "Month 3",
          "autoGenerated": false
        },
        {
          "id": "dce36",
          "from": "dcn40",
          "to": "dcn41",
          "branchLabel": "",
          "autoGenerated": false
        },
        {
          "id": "dce37",
          "from": "dcn39",
          "to": "dcn40",
          "branchLabel": "",
          "autoGenerated": false
        },
        {
          "id": "dce38",
          "from": "dcn32",
          "to": "dcn39",
          "branchLabel": "Month 6",
          "autoGenerated": false
        },
        {
          "id": "dce39",
          "from": "dcn43",
          "to": "dcn44",
          "branchLabel": "",
          "autoGenerated": false
        },
        {
          "id": "dce40",
          "from": "dcn42",
          "to": "dcn43",
          "branchLabel": "",
          "autoGenerated": false
        },
        {
          "id": "dce41",
          "from": "dcn32",
          "to": "dcn42",
          "branchLabel": "Month 12",
          "autoGenerated": false
        }
      ],
      "rootId": "dcn32"
    }
  },
  {
    "id": "DRIP-004",
    "name": "Reward Points Expiry Reminder",
    "issuer": "Yes Bank",
    "programs": [],
    "goal": {
      "eventCategory": "Transaction Events",
      "eventType": "Transaction",
      "conditions": []
    },
    "controlPct": 5,
    "status": "PAUSED",
    "root": {
      "nodes": {
        "dcn45": {
          "id": "dcn45",
          "type": "ENTRY_SCHEDULED",
          "label": "Monthly RP expiry scan",
          "meta": "1st of every month · RP expiring within 30 days",
          "autoGenerated": false
        },
        "dcn46": {
          "id": "dcn46",
          "type": "SEND",
          "label": "RP expiring soon",
          "meta": "WhatsApp · Template: rp_expiry_t30",
          "autoGenerated": false
        },
        "dcn47": {
          "id": "dcn47",
          "type": "WAIT_UNTIL",
          "label": "Redeemed?",
          "meta": "Wait up to 20 days for a redemption event",
          "autoGenerated": false
        },
        "dcn48": {
          "id": "dcn48",
          "type": "GOAL_EXIT",
          "label": "Redeemed",
          "meta": "",
          "autoGenerated": false
        },
        "dcn49": {
          "id": "dcn49",
          "type": "SEND",
          "label": "Last chance — RP expiring in 7 days",
          "meta": "SMS · Template: rp_expiry_t7",
          "autoGenerated": false
        },
        "dcn50": {
          "id": "dcn50",
          "type": "SPLIT",
          "label": "Redeemed?",
          "meta": "",
          "autoGenerated": false
        },
        "dcn51": {
          "id": "dcn51",
          "type": "GOAL_EXIT",
          "label": "Redeemed",
          "meta": "",
          "autoGenerated": false
        },
        "dcn52": {
          "id": "dcn52",
          "type": "EXIT",
          "label": "RP lapsed",
          "meta": "",
          "autoGenerated": false
        }
      },
      "edges": [
        {
          "id": "dce42",
          "from": "dcn47",
          "to": "dcn48",
          "branchLabel": "Yes",
          "autoGenerated": false
        },
        {
          "id": "dce43",
          "from": "dcn50",
          "to": "dcn51",
          "branchLabel": "Yes",
          "autoGenerated": false
        },
        {
          "id": "dce44",
          "from": "dcn50",
          "to": "dcn52",
          "branchLabel": "No",
          "autoGenerated": false
        },
        {
          "id": "dce45",
          "from": "dcn49",
          "to": "dcn50",
          "branchLabel": "",
          "autoGenerated": false
        },
        {
          "id": "dce46",
          "from": "dcn47",
          "to": "dcn49",
          "branchLabel": "No",
          "autoGenerated": false
        },
        {
          "id": "dce47",
          "from": "dcn46",
          "to": "dcn47",
          "branchLabel": "",
          "autoGenerated": false
        },
        {
          "id": "dce48",
          "from": "dcn45",
          "to": "dcn46",
          "branchLabel": "",
          "autoGenerated": false
        }
      ],
      "rootId": "dcn45"
    }
  },
  {
    "id": "DRIP-005",
    "name": "Auth Txn to EMI — Consent & Resolution",
    "issuer": "IndusInd Bank (IBL)",
    "programs": [],
    "goal": {
      "eventCategory": "EMI Events",
      "eventType": "EMI_STATUS_CHANGED",
      "conditions": [
        {
          "attribute": "New Status",
          "operator": "Equals",
          "value": "Successful"
        }
      ]
    },
    "controlPct": 10,
    "startDate": "",
    "endDate": "",
    "status": "PENDING_REVIEW",
    "root": {
      "nodes": {
        "dcn53": {
          "id": "dcn53",
          "type": "ENTRY_EVENT",
          "label": "Transaction",
          "meta": "Transaction Events · EMI Eligible = true",
          "autoGenerated": false
        },
        "dcn54": {
          "id": "dcn54",
          "type": "SEND",
          "label": "Consent Nudge",
          "meta": "WhatsApp · IBL-Karix-Txns · 11:00 · Template: Auth-to-EMI Consent WhatsApp",
          "autoGenerated": false
        },
        "dcn55": {
          "id": "dcn55",
          "type": "SPLIT",
          "label": "EMI_STATUS_CHANGED (New Status = Successful)?",
          "meta": "Goal check, auto-inserted after every Send",
          "autoGenerated": false
        },
        "dcn56": {
          "id": "dcn56",
          "type": "GOAL_EXIT",
          "label": "EMI_STATUS_CHANGED (New Status = Successful)",
          "meta": "",
          "autoGenerated": true
        },
        "dcn57": {
          "id": "dcn57",
          "type": "SPLIT",
          "label": "Previous step: Clicked?",
          "meta": "Custom condition split",
          "autoGenerated": false
        },
        "dcn58": {
          "id": "dcn58",
          "type": "WAIT_UNTIL",
          "label": "EMI_STATUS_CHANGED",
          "meta": "Timeout after 7 days · EMI Events",
          "autoGenerated": false
        },
        "dcn59": {
          "id": "dcn59",
          "type": "SPLIT",
          "label": "New Status = Successful?",
          "meta": "Outcome check, auto-inserted after Wait Until",
          "autoGenerated": true
        },
        "dcn60": {
          "id": "dcn60",
          "type": "GOAL_EXIT",
          "label": "EMI_STATUS_CHANGED (New Status = Successful)",
          "meta": "",
          "autoGenerated": true
        },
        "dcn61": {
          "id": "dcn61",
          "type": "EXIT",
          "label": "Resolved, but not to the goal outcome (New Status ≠ Successful)",
          "meta": "",
          "autoGenerated": false
        },
        "dcn62": {
          "id": "dcn62",
          "type": "EXIT",
          "label": "No resolution signal within 7 days — escalate to Ops for manual recon check",
          "meta": "",
          "autoGenerated": false
        },
        "dcn63": {
          "id": "dcn63",
          "type": "PAUSE",
          "label": "Wait 1 days",
          "meta": "",
          "autoGenerated": false
        },
        "dcn64": {
          "id": "dcn64",
          "type": "SEND",
          "label": "Reminder",
          "meta": "WhatsApp · IBL-Karix-Txns · 11:00 · Template: Auth-to-EMI Reminder WhatsApp",
          "autoGenerated": false
        },
        "dcn65": {
          "id": "dcn65",
          "type": "SPLIT",
          "label": "EMI_STATUS_CHANGED (New Status = Successful)?",
          "meta": "Goal check, auto-inserted after every Send",
          "autoGenerated": false
        },
        "dcn66": {
          "id": "dcn66",
          "type": "GOAL_EXIT",
          "label": "EMI_STATUS_CHANGED (New Status = Successful)",
          "meta": "",
          "autoGenerated": true
        },
        "dcn67": {
          "id": "dcn67",
          "type": "CHANNEL_FAILOVER",
          "label": "WhatsApp → SMS",
          "meta": "Retries on fallback if primary delivery fails",
          "autoGenerated": false
        },
        "dcn68": {
          "id": "dcn68",
          "type": "SEND",
          "label": "Final Reminder",
          "meta": "SMS · IBL-Karix-Txns · 11:00 · Template: EMI Conversion SMS",
          "autoGenerated": false
        },
        "dcn69": {
          "id": "dcn69",
          "type": "SPLIT",
          "label": "EMI_STATUS_CHANGED (New Status = Successful)?",
          "meta": "Goal check, auto-inserted after every Send",
          "autoGenerated": false
        },
        "dcn70": {
          "id": "dcn70",
          "type": "GOAL_EXIT",
          "label": "EMI_STATUS_CHANGED (New Status = Successful)",
          "meta": "",
          "autoGenerated": true
        },
        "dcn71": {
          "id": "dcn71",
          "type": "EXIT",
          "label": "No conversion after 3 touches",
          "meta": "",
          "autoGenerated": false
        }
      },
      "edges": [
        {
          "id": "dce49",
          "from": "dcn55",
          "to": "dcn56",
          "branchLabel": "Yes",
          "autoGenerated": true
        },
        {
          "id": "dce50",
          "from": "dcn59",
          "to": "dcn60",
          "branchLabel": "Yes",
          "autoGenerated": true
        },
        {
          "id": "dce51",
          "from": "dcn59",
          "to": "dcn61",
          "branchLabel": "No",
          "autoGenerated": false
        },
        {
          "id": "dce52",
          "from": "dcn58",
          "to": "dcn59",
          "branchLabel": "",
          "autoGenerated": true
        },
        {
          "id": "dce53",
          "from": "dcn58",
          "to": "dcn62",
          "branchLabel": "No",
          "autoGenerated": false
        },
        {
          "id": "dce54",
          "from": "dcn57",
          "to": "dcn58",
          "branchLabel": "Yes",
          "autoGenerated": false
        },
        {
          "id": "dce55",
          "from": "dcn65",
          "to": "dcn66",
          "branchLabel": "Yes",
          "autoGenerated": true
        },
        {
          "id": "dce56",
          "from": "dcn69",
          "to": "dcn70",
          "branchLabel": "Yes",
          "autoGenerated": true
        },
        {
          "id": "dce57",
          "from": "dcn69",
          "to": "dcn71",
          "branchLabel": "No",
          "autoGenerated": false
        },
        {
          "id": "dce58",
          "from": "dcn68",
          "to": "dcn69",
          "branchLabel": "",
          "autoGenerated": false
        },
        {
          "id": "dce59",
          "from": "dcn67",
          "to": "dcn68",
          "branchLabel": "",
          "autoGenerated": false
        },
        {
          "id": "dce60",
          "from": "dcn65",
          "to": "dcn67",
          "branchLabel": "No",
          "autoGenerated": false
        },
        {
          "id": "dce61",
          "from": "dcn64",
          "to": "dcn65",
          "branchLabel": "",
          "autoGenerated": false
        },
        {
          "id": "dce62",
          "from": "dcn63",
          "to": "dcn64",
          "branchLabel": "",
          "autoGenerated": false
        },
        {
          "id": "dce63",
          "from": "dcn57",
          "to": "dcn63",
          "branchLabel": "No",
          "autoGenerated": false
        },
        {
          "id": "dce64",
          "from": "dcn55",
          "to": "dcn57",
          "branchLabel": "No",
          "autoGenerated": false
        },
        {
          "id": "dce65",
          "from": "dcn54",
          "to": "dcn55",
          "branchLabel": "",
          "autoGenerated": false
        },
        {
          "id": "dce66",
          "from": "dcn53",
          "to": "dcn54",
          "branchLabel": "",
          "autoGenerated": false
        }
      ],
      "rootId": "dcn53"
    }
  },
  {
    "id": "DRIP-006",
    "name": "Card Issuance to Activation (Set PIN)",
    "issuer": "IndusInd Bank (IBL)",
    "programs": [],
    "goal": {
      "eventCategory": "Card Events",
      "eventType": "Card Activated",
      "conditions": []
    },
    "controlPct": 10,
    "startDate": "",
    "endDate": "",
    "status": "PENDING_REVIEW",
    "root": {
      "nodes": {
        "dcn72": {
          "id": "dcn72",
          "type": "ENTRY_EVENT",
          "label": "Card Issued",
          "meta": "Card Events",
          "autoGenerated": false
        },
        "dcn73": {
          "id": "dcn73",
          "type": "RANDOM_SPLIT",
          "label": "Channel Strategy Test",
          "meta": "WhatsApp-first 60% / SMS-first 40% allocation",
          "autoGenerated": false
        },
        "dcn74": {
          "id": "dcn74",
          "type": "SEND",
          "label": "Activate + Set PIN",
          "meta": "WhatsApp · IBL-Karix-Onb · 11:00 · Template: Card Activation WhatsApp",
          "autoGenerated": false
        },
        "dcn75": {
          "id": "dcn75",
          "type": "SPLIT",
          "label": "Card Activated?",
          "meta": "Goal check, auto-inserted after every Send",
          "autoGenerated": false
        },
        "dcn76": {
          "id": "dcn76",
          "type": "GOAL_EXIT",
          "label": "Card Activated",
          "meta": "",
          "autoGenerated": false
        },
        "dcn77": {
          "id": "dcn77",
          "type": "SPLIT",
          "label": "Previous step: Clicked?",
          "meta": "Custom condition split",
          "autoGenerated": false
        },
        "dcn78": {
          "id": "dcn78",
          "type": "PAUSE",
          "label": "Wait 1 days",
          "meta": "",
          "autoGenerated": false
        },
        "dcn79": {
          "id": "dcn79",
          "type": "SEND",
          "label": "Finish PIN Setup",
          "meta": "WhatsApp · IBL-Karix-Onb · 11:00 · Template: PIN Setup Reminder WhatsApp",
          "autoGenerated": false
        },
        "dcn80": {
          "id": "dcn80",
          "type": "SPLIT",
          "label": "Card Activated?",
          "meta": "Goal check, auto-inserted after every Send",
          "autoGenerated": false
        },
        "dcn81": {
          "id": "dcn81",
          "type": "GOAL_EXIT",
          "label": "Card Activated",
          "meta": "",
          "autoGenerated": false
        },
        "dcn82": {
          "id": "dcn82",
          "type": "EXIT",
          "label": "Started activation but did not finish PIN setup",
          "meta": "",
          "autoGenerated": false
        },
        "dcn83": {
          "id": "dcn83",
          "type": "PAUSE",
          "label": "Wait 2 days",
          "meta": "",
          "autoGenerated": false
        },
        "dcn84": {
          "id": "dcn84",
          "type": "CHANNEL_FAILOVER",
          "label": "WhatsApp → SMS",
          "meta": "Retries on fallback if primary delivery fails",
          "autoGenerated": false
        },
        "dcn85": {
          "id": "dcn85",
          "type": "SEND",
          "label": "Reminder",
          "meta": "SMS · IBL-Karix-Txns · 11:00 · Template: EMI Conversion SMS",
          "autoGenerated": false
        },
        "dcn86": {
          "id": "dcn86",
          "type": "SPLIT",
          "label": "Card Activated?",
          "meta": "Goal check, auto-inserted after every Send",
          "autoGenerated": false
        },
        "dcn87": {
          "id": "dcn87",
          "type": "GOAL_EXIT",
          "label": "Card Activated",
          "meta": "",
          "autoGenerated": false
        },
        "dcn88": {
          "id": "dcn88",
          "type": "EXIT",
          "label": "No engagement after 2 attempts",
          "meta": "",
          "autoGenerated": false
        },
        "dcn89": {
          "id": "dcn89",
          "type": "SEND",
          "label": "Activate + Set PIN (SMS)",
          "meta": "SMS · IBL-Karix-Txns · 11:00 · Template: EMI Conversion SMS",
          "autoGenerated": false
        },
        "dcn90": {
          "id": "dcn90",
          "type": "SPLIT",
          "label": "Card Activated?",
          "meta": "Goal check, auto-inserted after every Send",
          "autoGenerated": false
        },
        "dcn91": {
          "id": "dcn91",
          "type": "GOAL_EXIT",
          "label": "Card Activated",
          "meta": "",
          "autoGenerated": false
        },
        "dcn92": {
          "id": "dcn92",
          "type": "EXIT",
          "label": "No activation after SMS-first attempt",
          "meta": "",
          "autoGenerated": false
        }
      },
      "edges": [
        {
          "id": "dce67",
          "from": "dcn75",
          "to": "dcn76",
          "branchLabel": "Yes",
          "autoGenerated": false
        },
        {
          "id": "dce68",
          "from": "dcn80",
          "to": "dcn81",
          "branchLabel": "Yes",
          "autoGenerated": false
        },
        {
          "id": "dce69",
          "from": "dcn80",
          "to": "dcn82",
          "branchLabel": "No",
          "autoGenerated": false
        },
        {
          "id": "dce70",
          "from": "dcn79",
          "to": "dcn80",
          "branchLabel": "",
          "autoGenerated": false
        },
        {
          "id": "dce71",
          "from": "dcn78",
          "to": "dcn79",
          "branchLabel": "",
          "autoGenerated": false
        },
        {
          "id": "dce72",
          "from": "dcn77",
          "to": "dcn78",
          "branchLabel": "Yes",
          "autoGenerated": false
        },
        {
          "id": "dce73",
          "from": "dcn86",
          "to": "dcn87",
          "branchLabel": "Yes",
          "autoGenerated": false
        },
        {
          "id": "dce74",
          "from": "dcn86",
          "to": "dcn88",
          "branchLabel": "No",
          "autoGenerated": false
        },
        {
          "id": "dce75",
          "from": "dcn85",
          "to": "dcn86",
          "branchLabel": "",
          "autoGenerated": false
        },
        {
          "id": "dce76",
          "from": "dcn84",
          "to": "dcn85",
          "branchLabel": "",
          "autoGenerated": false
        },
        {
          "id": "dce77",
          "from": "dcn83",
          "to": "dcn84",
          "branchLabel": "",
          "autoGenerated": false
        },
        {
          "id": "dce78",
          "from": "dcn77",
          "to": "dcn83",
          "branchLabel": "No",
          "autoGenerated": false
        },
        {
          "id": "dce79",
          "from": "dcn75",
          "to": "dcn77",
          "branchLabel": "No",
          "autoGenerated": false
        },
        {
          "id": "dce80",
          "from": "dcn74",
          "to": "dcn75",
          "branchLabel": "",
          "autoGenerated": false
        },
        {
          "id": "dce81",
          "from": "dcn73",
          "to": "dcn74",
          "branchLabel": "WhatsApp-first (60%)",
          "autoGenerated": false
        },
        {
          "id": "dce82",
          "from": "dcn90",
          "to": "dcn91",
          "branchLabel": "Yes",
          "autoGenerated": false
        },
        {
          "id": "dce83",
          "from": "dcn90",
          "to": "dcn92",
          "branchLabel": "No",
          "autoGenerated": false
        },
        {
          "id": "dce84",
          "from": "dcn89",
          "to": "dcn90",
          "branchLabel": "",
          "autoGenerated": false
        },
        {
          "id": "dce85",
          "from": "dcn73",
          "to": "dcn89",
          "branchLabel": "SMS-first (40%)",
          "autoGenerated": false
        },
        {
          "id": "dce86",
          "from": "dcn72",
          "to": "dcn73",
          "branchLabel": "",
          "autoGenerated": false
        }
      ],
      "rootId": "dcn72"
    }
  }
];
