// React Flow custom node components, ported in spirit from dcNodeCardBodyHtml
// (the shared card-content builder the original used for both real
// rendering and its hidden-measurement probe). Handles are rendered but
// visually hidden (zero size) — this canvas has a fixed, dagre-computed
// layout with no user-draggable connections, so Handles exist only so
// React Flow can compute real edge attachment points, not as a visible
// interaction affordance.
import { Handle, Position } from '@xyflow/react';
import type { DcNodeType, DcNodeCategory } from '../data/nodeMeta';
import { DC_NODE_META } from '../data/nodeMeta';

const handleStyle: React.CSSProperties = { opacity: 0, width: 1, height: 1 };

export interface DripCardData {
  type: DcNodeType;
  label: string;
  meta: string;
  autoGenerated: boolean;
  shared: boolean; // reached by more than one incoming edge
  editable: boolean;
  onRemove?: () => void;
  [key: string]: unknown;
}

export function DripCardNode({ data }: { data: DripCardData }) {
  const cat: DcNodeCategory = DC_NODE_META[data.type].cat;
  return (
    <div className={`dc-node-card cat-${cat}${data.shared ? ' shared' : ''}${data.editable ? ' editable' : ''}`}>
      <Handle type="target" position={Position.Top} style={handleStyle} isConnectable={false} />
      {data.shared && <div className="dc-shared-badge">Reused</div>}
      {data.editable && data.onRemove && (
        <div className="dc-node-remove" onClick={data.onRemove}>
          ✕
        </div>
      )}
      <div className="dc-node-type">{DC_NODE_META[data.type].type}</div>
      <div className="dc-node-label">{data.label}</div>
      {data.meta && <div className="dc-node-meta">{data.meta}</div>}
      {data.autoGenerated && <div className="dc-auto-badge">↻ Auto-added</div>}
      <Handle type="source" position={Position.Bottom} style={handleStyle} isConnectable={false} />
    </div>
  );
}

export interface SlotData {
  editable: boolean;
  onAdd?: () => void;
  [key: string]: unknown;
}

export function SlotNode({ data }: { data: SlotData }) {
  return (
    <div className="dc-add-btn" onClick={data.editable ? data.onAdd : undefined} style={{ cursor: data.editable ? 'pointer' : 'default' }}>
      <Handle type="target" position={Position.Top} style={handleStyle} isConnectable={false} />
      +
    </div>
  );
}

export const dripNodeTypes = {
  dcCard: DripCardNode,
  dcSlot: SlotNode,
};
