// React Flow custom node components, ported in spirit from
// dcNodeCardBodyHtml. Handles are rendered but visually hidden (zero
// size) — this canvas has a fixed, dagre-computed layout with no
// user-draggable connections, so Handles exist only so React Flow can
// compute real edge attachment points, not as a visible interaction
// affordance.
import { Handle, Position } from '@xyflow/react';
import type { DcNodeType, DcNodeCategory } from '../data/nodeMeta';
import { DC_NODE_META } from '../data/nodeMeta';

const handleStyle: React.CSSProperties = { opacity: 0, width: 1, height: 1 };

export interface DripCardData {
  type: DcNodeType;
  label: string;
  meta: string;
  autoGenerated: boolean;
  shared: boolean; // reached by more than one incoming edge
  sharedCount: number;
  editable: boolean;
  isRoot: boolean;
  // Present only when autoGenerated — the id of the incoming edge whose
  // target is this node, so "click to replace" can remove exactly that
  // connection (the same data dcReplaceAutoNode needs).
  autoEdgeId?: string;
  onEdit?: () => void;
  onRemoveRoot?: () => void;
  onReplaceAuto?: (edgeId: string) => void;
  // Present only on the read-only Analytics view.
  stat?: string;
  engagement?: string;
  [key: string]: unknown;
}

export function DripCardNode({ data }: { data: DripCardData }) {
  const cat: DcNodeCategory = DC_NODE_META[data.type].cat;
  return (
    <div
      className={`dc-node-card cat-${cat}${data.shared ? ' shared' : ''}${data.editable ? ' editable' : ''}`}
      onClick={data.editable ? data.onEdit : undefined}
      style={{ cursor: data.editable ? 'pointer' : 'default', position: 'relative' }}
      title={data.editable ? 'Click to edit this step' : undefined}
    >
      <Handle type="target" position={Position.Top} style={handleStyle} isConnectable={false} />
      {data.shared && <div className="dc-shared-badge">Reused in {data.sharedCount} places</div>}
      {data.editable && data.isRoot && (
        <div
          className="dc-node-remove"
          onClick={(e) => {
            e.stopPropagation();
            data.onRemoveRoot?.();
          }}
          title="Remove entry"
        >
          ✕
        </div>
      )}
      <div className="dc-node-type">{DC_NODE_META[data.type].type}</div>
      <div className="dc-node-label">{data.label}</div>
      {data.meta && <div className="dc-node-meta">{data.meta}</div>}
      {data.stat && (
        <div className="dc-node-stat">
          <span>{data.stat}</span>
        </div>
      )}
      {data.engagement && <div className="dc-node-engagement">{data.engagement}</div>}
      {data.editable && data.autoGenerated && data.autoEdgeId && (
        <div
          className="dc-auto-badge"
          onClick={(e) => {
            e.stopPropagation();
            data.onReplaceAuto?.(data.autoEdgeId!);
          }}
          title="Auto-added — click to replace with your own step"
        >
          ↻ Auto-added, click to replace
        </div>
      )}
      <Handle type="source" position={Position.Bottom} style={handleStyle} isConnectable={false} />
    </div>
  );
}

export interface SlotData {
  editable: boolean;
  onAdd?: () => void;
  [key: string]: unknown;
}

export function SlotNode({ data }: { data: SlotData }) {
  return (
    <div className="dc-add-btn" onClick={data.editable ? data.onAdd : undefined} style={{ cursor: data.editable ? 'pointer' : 'default' }} title="Add next step">
      <Handle type="target" position={Position.Top} style={handleStyle} isConnectable={false} />
      +
    </div>
  );
}

export const dripNodeTypes = {
  dcCard: DripCardNode,
  dcSlot: SlotNode,
};
