// React Flow custom node components, ported in spirit from
// dcNodeCardBodyHtml. Handles are rendered but visually hidden (zero
// size) — this canvas has a fixed, dagre-computed layout with no
// user-draggable connections, so Handles exist only so React Flow can
// compute real edge attachment points, not as a visible interaction
// affordance.
import { Handle, Position } from '@xyflow/react';
import type { DcNodeType, DcNodeCategory } from '../data/nodeMeta';
import { DC_NODE_META, DC_CATEGORY_ICON } from '../data/nodeMeta';
import { Icon } from '../components/icons';

const handleStyle: React.CSSProperties = { opacity: 0, width: 1, height: 1 };

const DC_CHANNEL_ICON: Record<string, string> = {
  WHATSAPP: 'whatsapp',
  SMS: 'sms',
  EMAIL: 'mail',
  RCS: 'rcs',
};
const DC_CHANNEL_LABEL: Record<string, string> = {
  WHATSAPP: 'WhatsApp',
  SMS: 'SMS',
  EMAIL: 'E-mail',
  RCS: 'RCS',
};

export interface DripCardData {
  type: DcNodeType;
  label: string;
  meta: string;
  autoGenerated: boolean;
  shared: boolean; // reached by more than one incoming edge
  sharedCount: number;
  editable: boolean;
  isRoot: boolean;
  // Set only for a SEND node — its configured channel, used to pick a
  // channel-specific icon instead of the generic category one (the
  // channel is the single most glance-relevant fact about a Send, more
  // so than "this is a Send" itself, which the SEND text label already
  // states).
  channel?: string;
  // Set only for a SEND node whose config has a fallback channel
  // configured — its own value (not just a yes/no flag), so the card can
  // show which channel it actually falls back to, not just that one
  // exists.
  fallbackChannel?: string;
  // Send-only structured rows (node-design refinement pass) — each its
  // own line with its own icon, derived straight from _config at render
  // time (toFlowElements.ts), not folded into the generic `meta` string
  // every other node type still uses. templateName is omitted entirely
  // when it's identical to the step name; fallbackTemplateName is only
  // ever set alongside fallbackChannel.
  templateName?: string;
  timingLabel?: string;
  fallbackTemplateName?: string;
  // Present only when autoGenerated — the id of the incoming edge whose
  // target is this node, so "click to replace" can remove exactly that
  // connection (the same data dcReplaceAutoNode needs).
  autoEdgeId?: string;
  onEdit?: () => void;
  onRemoveRoot?: () => void;
  onReplaceAuto?: (edgeId: string) => void;
  // True only for a SPLIT that's still exactly the untouched,
  // auto-inserted goal-check shape (see dcIsAutoGoalCheckSplit) — lets
  // it be collapsed back out entirely (not just one branch) when there's
  // nothing worth checking at this point, without offering that same
  // affordance on a Split the user built themselves.
  isAutoGoalCheck?: boolean;
  onRemoveGoalCheck?: () => void;
  // Set for any non-auto-generated node with exactly one incoming edge
  // (never a shared/merged one — the shared badge already owns that
  // case) — the id of that edge, so a visible "remove" badge on the card
  // itself can detach it (and, via the usual garbage collection,
  // whatever's uniquely built underneath). The only other way to remove
  // a step is hovering the thin, often-unlabeled connector line leading
  // into it and finding its own opacity-0-until-hover "✕" — a control
  // nobody discovers by accident, unlike hovering a big card (the same
  // reasoning the root's own dc-node-remove button is built on).
  removableEdgeId?: string;
  onRemoveEdge?: (edgeId: string) => void;
  // Present only on the read-only Analytics view.
  stat?: string;
  engagement?: string;
  // Ordered left-to-right, one id per outgoing edge — only set when this
  // node has 2+ outgoing edges (a Split). See toFlowElements.ts for why:
  // a single shared centered handle makes every branch's label chip
  // midpoint move only half as far as its target, which is what caused
  // chips to overlap regardless of how much width the layout reserved.
  outgoingHandleIds?: string[];
  [key: string]: unknown;
}

export function DripCardNode({ data }: { data: DripCardData }) {
  const meta = DC_NODE_META[data.type];
  const cat: DcNodeCategory = meta.cat;
  const isEntry = cat === 'entry';
  const typeIcon = data.type === 'SEND' && data.channel && DC_CHANNEL_ICON[data.channel] ? DC_CHANNEL_ICON[data.channel] : DC_CATEGORY_ICON[cat];
  // Once the icon carries the channel, the meta line below no longer
  // repeats it as text (see labelMeta.ts) — this title is the one place
  // that fact is still spelled out, for anyone hovering who doesn't
  // recognize the glyph yet.
  const channelTitle = data.type === 'SEND' && data.channel ? `${DC_CHANNEL_LABEL[data.channel]} · Primary channel` : undefined;
  const fallbackTitle =
    data.fallbackChannel && data.channel ? `${DC_CHANNEL_LABEL[data.fallbackChannel]} · Fallback if ${DC_CHANNEL_LABEL[data.channel]} delivery fails` : undefined;
  // Whenever a hover remove "✕" can appear on this card (root entry, or
  // a single-incoming-edge step), the identity row permanently reserves
  // its footprint — fixed at the shared component level, not per node
  // type, so short type labels (e.g. "ENTRY · EVENT" + START) can never
  // visually collide with it on hover. Reserving the gutter all the
  // time (not just on :hover) avoids a layout shift on hover, which
  // would read as janky on its own.
  const hasRemoveAffordance = data.editable && (data.isRoot || !!data.removableEdgeId);
  return (
    <div
      className={`dc-node-card cat-${cat} size-${meta.size}${data.shared ? ' shared' : ''}${data.editable ? ' editable' : ''}${hasRemoveAffordance ? ' has-remove' : ''}`}
      onClick={data.editable ? data.onEdit : undefined}
      style={{ cursor: data.editable ? 'pointer' : 'default', position: 'relative' }}
      title={data.editable ? 'Click to edit this step' : undefined}
    >
      <Handle type="target" position={Position.Top} style={handleStyle} isConnectable={false} />
      {data.shared && (
        <div className="dc-shared-badge" title={`Used in ${data.sharedCount} places`}>
          ↗ {data.sharedCount}
        </div>
      )}
      {data.editable && data.isRoot && (
        <div
          className="dc-node-remove"
          onClick={(e) => {
            e.stopPropagation();
            data.onRemoveRoot?.();
          }}
          title="Remove entry"
        >
          ✕
        </div>
      )}
      {data.editable && data.removableEdgeId && (
        <div
          className="dc-node-remove"
          onClick={(e) => {
            e.stopPropagation();
            data.onRemoveEdge?.(data.removableEdgeId!);
          }}
          title="Remove this step"
        >
          ✕
        </div>
      )}
      {/* Identity row — icon + type label + (Entry only) START, all in
          normal left-to-right flow. Nothing here is pushed to the card's
          right edge: the top-right corner is reserved exclusively for
          the hover-only remove "✕" (node-design refinement pass). */}
      <div className="dc-node-type">
        <span className="dc-node-channel-icon" title={channelTitle}>
          <Icon name={typeIcon} />
        </span>
        <span>{meta.type}</span>
        {isEntry && <span className="dc-node-start-tag">START</span>}
      </div>
      <div className="dc-node-label" title={data.label}>{data.label}</div>
      {data.type === 'SEND' ? (
        <>
          {data.templateName && (
            <div className="dc-node-send-row" title={data.templateName}>
              <Icon name="file" />
              <span>{data.templateName}</span>
            </div>
          )}
          {data.timingLabel && (
            <div className="dc-node-send-row" title={data.timingLabel}>
              <Icon name="clock" />
              <span>{data.timingLabel}</span>
            </div>
          )}
          {data.fallbackChannel && DC_CHANNEL_ICON[data.fallbackChannel] && (
            <div className="dc-node-send-row dc-node-fallback-row" title={fallbackTitle}>
              <span className="dc-node-fallback-arrow">↳</span>
              <Icon name={DC_CHANNEL_ICON[data.fallbackChannel]} />
              <span>{data.fallbackTemplateName || DC_CHANNEL_LABEL[data.fallbackChannel]}</span>
            </div>
          )}
        </>
      ) : (
        data.meta && (
          <div className="dc-node-meta" title={data.meta}>
            {data.meta}
          </div>
        )
      )}
      {data.stat && (
        <div className="dc-node-stat">
          <span>{data.stat}</span>
        </div>
      )}
      {data.engagement && <div className="dc-node-engagement">{data.engagement}</div>}
      {data.editable && data.autoGenerated && data.autoEdgeId && (
        <div
          className="dc-auto-badge dc-replace-badge"
          onClick={(e) => {
            e.stopPropagation();
            data.onReplaceAuto?.(data.autoEdgeId!);
          }}
          title="System step — tap to customize"
        >
          ↻ System step · Customize
        </div>
      )}
      {data.editable && data.isAutoGoalCheck && (
        <div
          className="dc-auto-badge dc-goalcheck-badge"
          onClick={(e) => {
            e.stopPropagation();
            data.onRemoveGoalCheck?.();
          }}
          title="Remove this goal check, keeping whatever comes next"
        >
          Remove goal check
        </div>
      )}
      {data.outgoingHandleIds && data.outgoingHandleIds.length > 1 ? (
        data.outgoingHandleIds.map((id, i) => (
          <Handle
            key={id}
            type="source"
            id={id}
            position={Position.Bottom}
            style={{ ...handleStyle, left: `${((i + 0.5) / data.outgoingHandleIds!.length) * 100}%` }}
            isConnectable={false}
          />
        ))
      ) : (
        <Handle type="source" position={Position.Bottom} style={handleStyle} isConnectable={false} />
      )}
    </div>
  );
}

export interface SlotData {
  editable: boolean;
  onAdd?: () => void;
  [key: string]: unknown;
}

export function SlotNode({ data }: { data: SlotData }) {
  return (
    <div className="dc-add-btn" onClick={data.editable ? data.onAdd : undefined} style={{ cursor: data.editable ? 'pointer' : 'default' }} title="Add next step">
      <Handle type="target" position={Position.Top} style={handleStyle} isConnectable={false} />
      +
    </div>
  );
}

export const dripNodeTypes = {
  dcCard: DripCardNode,
  dcSlot: SlotNode,
};
