// Converts a DripGraph into React Flow's Node[]/Edge[] shape — the
// render-layer adapter the migration plan calls out (from/to -> source/
// target), kept separate from the canonical DripGraph shape so the
// reducer never needs to know React Flow exists.
import type { Node, Edge } from '@xyflow/react';
import type { DripGraph } from '../data/graphTypes';
import { computeDagreLayout, DC_CARD_W, DC_SLOT_SIZE, DC_CARD_H_FALLBACK } from './layoutGraph';
import type { DripCardData } from './nodeTypes';
import type { DripEdgeData } from './DripEdge';

export interface ToFlowOptions {
  editable: boolean;
  measuredHeights?: Record<string, number>;
  onRemoveNode?: (nodeId: string) => void;
  onRemoveEdge?: (edgeId: string) => void;
  onAddAtEdge?: (edgeId: string) => void;
}

export function graphToFlowElements(graph: DripGraph, opts: ToFlowOptions): { nodes: Node[]; edges: Edge[] } {
  if (!graph.rootId) return { nodes: [], edges: [] };

  const incoming: Record<string, number> = {};
  graph.edges.forEach((e) => {
    if (e.to) incoming[e.to] = (incoming[e.to] || 0) + 1;
  });

  const { positions, slotIds } = computeDagreLayout(graph, opts.measuredHeights || {});

  const nodes: Node[] = Object.values(graph.nodes).map((nd) => {
    const pos = positions[nd.id] || { x: 0, y: 0, width: DC_CARD_W, height: DC_CARD_H_FALLBACK };
    const data: DripCardData = {
      type: nd.type,
      label: nd.label,
      meta: nd.meta,
      autoGenerated: nd.autoGenerated,
      shared: (incoming[nd.id] || 0) > 1,
      editable: opts.editable,
      onRemove: opts.onRemoveNode ? () => opts.onRemoveNode!(nd.id) : undefined,
    };
    return {
      id: nd.id,
      type: 'dcCard',
      position: { x: pos.x, y: pos.y },
      data,
      draggable: false,
      selectable: false,
    };
  });

  const slotNodes: Node[] = graph.edges
    .filter((e) => e.to === null)
    .map((e) => {
      const slotId = slotIds[e.id];
      const pos = positions[slotId] || { x: 0, y: 0 };
      return {
        id: slotId,
        type: 'dcSlot',
        position: { x: pos.x, y: pos.y },
        data: { editable: opts.editable, onAdd: opts.onAddAtEdge ? () => opts.onAddAtEdge!(e.id) : undefined },
        draggable: false,
        selectable: false,
        width: DC_SLOT_SIZE,
        height: DC_SLOT_SIZE,
      };
    });

  const edges: Edge[] = graph.edges.map((e) => {
    const data: DripEdgeData = {
      branchLabel: e.branchLabel,
      editable: opts.editable,
      onRemove: opts.onRemoveEdge ? () => opts.onRemoveEdge!(e.id) : undefined,
    };
    return {
      id: e.id,
      source: e.from,
      target: e.to || slotIds[e.id],
      type: 'dcEdge',
      data,
    };
  });

  return { nodes: [...nodes, ...slotNodes], edges };
}
