// Converts a DripGraph into React Flow's Node[]/Edge[] shape — the
// render-layer adapter the migration plan calls out (from/to -> source/
// target), kept separate from the canonical DripGraph shape so the
// reducer never needs to know React Flow exists.
import type { Node, Edge } from '@xyflow/react';
import type { DripGraph } from '../data/graphTypes';
import { dcIsGoalCheckNode } from '../reducer/campaignReducer';
import { COMMS_TEMPLATES } from '../data/sharedConstants';
import { computeDagreLayout, DC_CARD_W, DC_SLOT_SIZE, DC_CARD_H_FALLBACK } from './layoutGraph';
import type { DripCardData } from './nodeTypes';
import type { DripEdgeData } from './DripEdge';

// 24h "HH:MM" (native <input type=time>'s own format) -> "H:MM AM/PM" for
// canvas display only — the stored config stays 24h, this is purely a
// render-time format (node-design refinement: ambiguous "11:00" must read
// unambiguously as a time of day).
function formatAbsTime(t: string): string {
  if (!t) return '';
  const [hStr, mStr] = t.split(':');
  const h = parseInt(hStr, 10);
  if (Number.isNaN(h)) return t;
  const ampm = h >= 12 ? 'PM' : 'AM';
  const h12 = h % 12 || 12;
  return `${h12}:${mStr} ${ampm}`;
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function formatSendTiming(p: any): string {
  if (p.timing === 'Absolute') return formatAbsTime(p.absTime);
  return `${p.relativeDuration} ${p.relativeUnit} after ${p.relativeAnchor}`;
}

export interface DripCanvasMetrics {
  nodeCounts: Record<string, number>;
  edgeCounts: Record<string, { count: number; pct: number }>;
  engagementByNodeId?: Record<string, { deliveredPct: number; openedPct: number; clickedPct: number }>;
}

export interface ToFlowOptions {
  editable: boolean;
  measuredHeights?: Record<string, number>;
  onEditNode?: (nodeId: string) => void;
  onRemoveRoot?: () => void;
  onReplaceAuto?: (edgeId: string) => void;
  onRemoveEdge?: (edgeId: string) => void;
  onAddAtEdge?: (edgeId: string) => void;
  onAddAtGrowLeaf?: (nodeId: string) => void;
  onAddAtMidEdge?: (edgeId: string) => void;
  onRemoveGoalCheck?: (nodeId: string) => void;
  // Present only on the read-only Analytics view — annotates nodes/edges
  // with live counts instead of changing anything about layout/editing.
  metrics?: DripCanvasMetrics;
}

function fmtCount(n: number): string {
  return n.toLocaleString('en-IN');
}

export function graphToFlowElements(graph: DripGraph, opts: ToFlowOptions): { nodes: Node[]; edges: Edge[] } {
  if (!graph.rootId) return { nodes: [], edges: [] };

  const incoming: Record<string, number> = {};
  graph.edges.forEach((e) => {
    if (e.to) incoming[e.to] = (incoming[e.to] || 0) + 1;
  });

  const { positions, slotIds, growSlotIds } = computeDagreLayout(graph, opts.measuredHeights || {});

  // A node with 2+ outgoing edges (Decision/Random/Conditional Split) must
  // give each branch its own source handle, spread across the node's
  // width in the same left-to-right order as its target — React Flow's
  // default is one single centered handle shared by every outgoing edge,
  // which makes each edge's rendered label midpoint `(sourceX+targetX)/2`
  // move only HALF as far as its target does (the shared source term
  // never moves). That silently halves the effective spacing a branch
  // label chip gets relative to what dagre reserved for its slot, which
  // is what caused chips to overlap even when the slot layout itself had
  // no overlap at all. A single node with only one outgoing edge keeps
  // the plain default (unlabeled) handle — no behavior change there.
  const targetCenterX = (e: (typeof graph.edges)[number]): number => {
    const id = e.to || slotIds[e.id];
    const p = positions[id];
    return p ? p.x + p.width / 2 : 0;
  };
  const outgoingHandleId: Record<string, string> = {}; // edgeId -> handleId
  const outgoingHandleIdsByNode: Record<string, string[]> = {};
  Object.values(graph.nodes).forEach((nd) => {
    const outs = graph.edges.filter((e) => e.from === nd.id);
    if (outs.length <= 1) return;
    const sorted = [...outs].sort((a, b) => targetCenterX(a) - targetCenterX(b));
    const ids = sorted.map((_, i) => `${nd.id}__src${i}`);
    outgoingHandleIdsByNode[nd.id] = ids;
    sorted.forEach((e, i) => {
      outgoingHandleId[e.id] = ids[i];
    });
  });

  const nodes: Node[] = Object.values(graph.nodes).map((nd) => {
    const pos = positions[nd.id] || { x: 0, y: 0, width: DC_CARD_W, height: DC_CARD_H_FALLBACK };
    // GOAL_CHECK is always autoGenerated but never gets the generic
    // "replace" badge (its own dedicated "remove goal check" badge below
    // is the correct, more precise operation for it — collapsing it out
    // entirely while preserving whatever's built under "No").
    const autoEdge = nd.autoGenerated && !dcIsGoalCheckNode(nd) ? graph.edges.find((e) => e.to === nd.id) : undefined;
    // Any node reached by exactly one real connection can be removed via
    // a visible badge on its own card — excluding auto-generated nodes
    // (GOAL_CHECK has its own dedicated badge that removes just the
    // check while preserving whatever's built under "No"; other
    // auto-generated nodes get the "replace" badge above instead). A
    // shared node (2+ incoming) keeps relying on removing one specific
    // edge instead — which connection "the" remove button would mean is
    // ambiguous once there's more than one.
    const removableEdge = !nd.autoGenerated && (incoming[nd.id] || 0) === 1 ? graph.edges.find((e) => e.to === nd.id) : undefined;
    const count = opts.metrics?.nodeCounts[nd.id];
    const engagement = opts.metrics?.engagementByNodeId?.[nd.id];
    // Send's template/timing/fallback-template are derived straight from
    // _config at render time, not from the stored meta string — they're
    // each their own row with their own icon now (node-design refinement
    // pass), not a single flattened " · "-joined line.
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const sendConfig = nd.type === 'SEND' ? (nd._config as any) : null;
    const templateName = sendConfig ? COMMS_TEMPLATES.find((x) => x.id === sendConfig.templateId)?.name : undefined;
    const fallbackTemplateName = sendConfig?.fallbackChannel ? COMMS_TEMPLATES.find((x) => x.id === sendConfig.fallbackTemplateId)?.name : undefined;
    const data: DripCardData = {
      type: nd.type,
      label: nd.label,
      meta: nd.meta,
      autoGenerated: nd.autoGenerated,
      shared: (incoming[nd.id] || 0) > 1,
      sharedCount: incoming[nd.id] || 0,
      editable: opts.editable,
      isRoot: graph.rootId === nd.id,
      channel: sendConfig?.channel,
      fallbackChannel: sendConfig?.fallbackChannel || undefined,
      // Suppressed when identical to the step name (label) — no point
      // saying the same thing twice in two different weights.
      templateName: templateName && templateName !== nd.label ? templateName : undefined,
      timingLabel: sendConfig ? formatSendTiming(sendConfig) : undefined,
      fallbackTemplateName,
      autoEdgeId: autoEdge?.id,
      onEdit: opts.onEditNode ? () => opts.onEditNode!(nd.id) : undefined,
      onRemoveRoot: opts.onRemoveRoot,
      onReplaceAuto: opts.onReplaceAuto,
      isAutoGoalCheck: dcIsGoalCheckNode(nd),
      onRemoveGoalCheck: opts.onRemoveGoalCheck ? () => opts.onRemoveGoalCheck!(nd.id) : undefined,
      removableEdgeId: removableEdge?.id,
      onRemoveEdge: opts.onRemoveEdge,
      stat: count !== undefined ? `${fmtCount(count)} reached` : undefined,
      engagement: engagement ? `${engagement.deliveredPct}% delivered · ${engagement.openedPct}% opened · ${engagement.clickedPct}% clicked` : undefined,
      outgoingHandleIds: outgoingHandleIdsByNode[nd.id],
    };
    return {
      id: nd.id,
      type: 'dcCard',
      position: { x: pos.x, y: pos.y },
      data,
    };
  });

  // A slot's dagre LAYOUT width (from estimateSlotWidth, see
  // layoutGraph.ts) is reserved purely so a branch-label chip has room
  // to sit beside it without colliding with its neighbors — it's never
  // the slot's own rendered size, which is always a fixed DC_SLOT_SIZE
  // "+" button. `positions[slotId].x` is that reserved box's LEFT edge;
  // placing the real, narrower button there instead of centering it
  // within the box leaves it offset toward the left by half the
  // difference, which is exactly what produced a zigzagging connector
  // down to it instead of a straight line — most visible on a plain,
  // unlabeled slot (zero chip, but still reserved the same floor width),
  // since there's no chip to visually "explain" the extra space.
  const centeredSlotX = (pos: { x: number; width: number }) => pos.x + (pos.width - DC_SLOT_SIZE) / 2;

  const openSlotNodes: Node[] = graph.edges
    .filter((e) => e.to === null)
    .map((e) => {
      const slotId = slotIds[e.id];
      const pos = positions[slotId] || { x: 0, y: 0, width: DC_SLOT_SIZE };
      return {
        id: slotId,
        type: 'dcSlot',
        position: { x: centeredSlotX(pos), y: pos.y },
        data: { editable: opts.editable, onAdd: opts.onAddAtEdge ? () => opts.onAddAtEdge!(e.id) : undefined },
        width: DC_SLOT_SIZE,
        height: DC_SLOT_SIZE,
      };
    });

  const growSlotNodes: Node[] = Object.entries(growSlotIds).map(([nodeId, slotId]) => {
    const pos = positions[slotId] || { x: 0, y: 0, width: DC_SLOT_SIZE };
    return {
      id: slotId,
      type: 'dcSlot',
      position: { x: centeredSlotX(pos), y: pos.y },
      data: { editable: opts.editable, onAdd: opts.onAddAtGrowLeaf ? () => opts.onAddAtGrowLeaf!(nodeId) : undefined },
      width: DC_SLOT_SIZE,
      height: DC_SLOT_SIZE,
    };
  });

  const realEdges: Edge[] = graph.edges.map((e) => {
    const stat = opts.metrics?.edgeCounts[e.id];
    const data: DripEdgeData = {
      branchLabel: e.branchLabel,
      editable: opts.editable,
      onRemove: opts.onRemoveEdge ? () => opts.onRemoveEdge!(e.id) : undefined,
      // Mid-insert only makes sense on an edge that already connects two
      // real nodes — a dangling open-slot edge already has its own "+"
      // slot node for this.
      onInsert: opts.onAddAtMidEdge && e.to ? () => opts.onAddAtMidEdge!(e.id) : undefined,
      statLabel: stat ? `${stat.pct}% · ${fmtCount(stat.count)}` : undefined,
    };
    return {
      id: e.id,
      source: e.from,
      sourceHandle: outgoingHandleId[e.id],
      target: e.to || slotIds[e.id],
      type: 'dcEdge',
      data,
    };
  });

  // Plain connector lines from a grow-leaf node down to its own "+" —
  // never labeled, never removable on their own (removing the leaf's
  // whole subtree happens via whichever edge feeds INTO the leaf, not
  // this slot connector).
  const growEdges: Edge[] = Object.entries(growSlotIds).map(([nodeId, slotId]) => ({
    id: 'growedge_' + nodeId,
    source: nodeId,
    target: slotId,
    type: 'dcEdge',
    data: { branchLabel: '', editable: false } as DripEdgeData,
  }));

  return { nodes: [...nodes, ...openSlotNodes, ...growSlotNodes], edges: [...realEdges, ...growEdges] };
}
