// Converts a DripGraph into React Flow's Node[]/Edge[] shape — the
// render-layer adapter the migration plan calls out (from/to -> source/
// target), kept separate from the canonical DripGraph shape so the
// reducer never needs to know React Flow exists.
import type { Node, Edge } from '@xyflow/react';
import type { DripGraph } from '../data/graphTypes';
import { computeDagreLayout, DC_CARD_W, DC_SLOT_SIZE, DC_CARD_H_FALLBACK } from './layoutGraph';
import type { DripCardData } from './nodeTypes';
import type { DripEdgeData } from './DripEdge';

export interface DripCanvasMetrics {
  nodeCounts: Record<string, number>;
  edgeCounts: Record<string, { count: number; pct: number }>;
  engagementByNodeId?: Record<string, { deliveredPct: number; openedPct: number; clickedPct: number }>;
}

export interface ToFlowOptions {
  editable: boolean;
  measuredHeights?: Record<string, number>;
  onEditNode?: (nodeId: string) => void;
  onRemoveRoot?: () => void;
  onReplaceAuto?: (edgeId: string) => void;
  onRemoveEdge?: (edgeId: string) => void;
  onAddAtEdge?: (edgeId: string) => void;
  onAddAtGrowLeaf?: (nodeId: string) => void;
  onAddAtMidEdge?: (edgeId: string) => void;
  // Present only on the read-only Analytics view — annotates nodes/edges
  // with live counts instead of changing anything about layout/editing.
  metrics?: DripCanvasMetrics;
}

function fmtCount(n: number): string {
  return n.toLocaleString('en-IN');
}

export function graphToFlowElements(graph: DripGraph, opts: ToFlowOptions): { nodes: Node[]; edges: Edge[] } {
  if (!graph.rootId) return { nodes: [], edges: [] };

  const incoming: Record<string, number> = {};
  graph.edges.forEach((e) => {
    if (e.to) incoming[e.to] = (incoming[e.to] || 0) + 1;
  });

  const { positions, slotIds, growSlotIds } = computeDagreLayout(graph, opts.measuredHeights || {});

  const nodes: Node[] = Object.values(graph.nodes).map((nd) => {
    const pos = positions[nd.id] || { x: 0, y: 0, width: DC_CARD_W, height: DC_CARD_H_FALLBACK };
    const autoEdge = nd.autoGenerated ? graph.edges.find((e) => e.to === nd.id) : undefined;
    const count = opts.metrics?.nodeCounts[nd.id];
    const engagement = opts.metrics?.engagementByNodeId?.[nd.id];
    const data: DripCardData = {
      type: nd.type,
      label: nd.label,
      meta: nd.meta,
      autoGenerated: nd.autoGenerated,
      shared: (incoming[nd.id] || 0) > 1,
      sharedCount: incoming[nd.id] || 0,
      editable: opts.editable,
      isRoot: graph.rootId === nd.id,
      autoEdgeId: autoEdge?.id,
      onEdit: opts.onEditNode ? () => opts.onEditNode!(nd.id) : undefined,
      onRemoveRoot: opts.onRemoveRoot,
      onReplaceAuto: opts.onReplaceAuto,
      stat: count !== undefined ? `${fmtCount(count)} reached` : undefined,
      engagement: engagement ? `${engagement.deliveredPct}% delivered · ${engagement.openedPct}% opened · ${engagement.clickedPct}% clicked` : undefined,
    };
    return {
      id: nd.id,
      type: 'dcCard',
      position: { x: pos.x, y: pos.y },
      data,
    };
  });

  const openSlotNodes: Node[] = graph.edges
    .filter((e) => e.to === null)
    .map((e) => {
      const slotId = slotIds[e.id];
      const pos = positions[slotId] || { x: 0, y: 0 };
      return {
        id: slotId,
        type: 'dcSlot',
        position: { x: pos.x, y: pos.y },
        data: { editable: opts.editable, onAdd: opts.onAddAtEdge ? () => opts.onAddAtEdge!(e.id) : undefined },
        width: DC_SLOT_SIZE,
        height: DC_SLOT_SIZE,
      };
    });

  const growSlotNodes: Node[] = Object.entries(growSlotIds).map(([nodeId, slotId]) => {
    const pos = positions[slotId] || { x: 0, y: 0 };
    return {
      id: slotId,
      type: 'dcSlot',
      position: { x: pos.x, y: pos.y },
      data: { editable: opts.editable, onAdd: opts.onAddAtGrowLeaf ? () => opts.onAddAtGrowLeaf!(nodeId) : undefined },
      width: DC_SLOT_SIZE,
      height: DC_SLOT_SIZE,
    };
  });

  const realEdges: Edge[] = graph.edges.map((e) => {
    const stat = opts.metrics?.edgeCounts[e.id];
    const data: DripEdgeData = {
      branchLabel: e.branchLabel,
      editable: opts.editable,
      onRemove: opts.onRemoveEdge ? () => opts.onRemoveEdge!(e.id) : undefined,
      // Mid-insert only makes sense on an edge that already connects two
      // real nodes — a dangling open-slot edge already has its own "+"
      // slot node for this.
      onInsert: opts.onAddAtMidEdge && e.to ? () => opts.onAddAtMidEdge!(e.id) : undefined,
      statLabel: stat ? `${stat.pct}% · ${fmtCount(stat.count)}` : undefined,
    };
    return {
      id: e.id,
      source: e.from,
      target: e.to || slotIds[e.id],
      type: 'dcEdge',
      data,
    };
  });

  // Plain connector lines from a grow-leaf node down to its own "+" —
  // never labeled, never removable on their own (removing the leaf's
  // whole subtree happens via whichever edge feeds INTO the leaf, not
  // this slot connector).
  const growEdges: Edge[] = Object.entries(growSlotIds).map(([nodeId, slotId]) => ({
    id: 'growedge_' + nodeId,
    source: nodeId,
    target: slotId,
    type: 'dcEdge',
    data: { branchLabel: '', editable: false } as DripEdgeData,
  }));

  return { nodes: [...nodes, ...openSlotNodes, ...growSlotNodes], edges: [...realEdges, ...growEdges] };
}
